[Feature/#928] 로그인 중앙화 UI 구현
sopt-makers/sopt-android pull request #1008
Opened 2024-12-25 00:04 UTC by leeeyubin

- closed #928
## What is this issue?
- [x] 로그인 중앙화 UI 작업
- [x] 로그인 화면 Compose로 마이그레이션

## Screenshot
| 로그인 화면 <br>`AuthActivity` | 회원 인증 화면 <br> `CertificateMemberScreen` |
|:-------:|:---------------:|
| <video src="https://github.com/user-attachments/assets/0ff2eedd-0777-4a39-bf66-77a94a7da4dc" width=100> | <video src="https://github.com/user-attachments/assets/c140f654-acbf-423a-bfeb-3fc30ad56f1d" width=100/> | 

| 로그인 오류 화면 <br> `AuthErrorScreen` | 전화번호 인증 화면 <br> `CertificateAccountScreen`|  소셜계정 설정 화면 <br> `ChangeAccountScreen`  |
|:-------:|:----------------------:|:----------------------:|
| <image src="https://github.com/user-attachments/assets/e99fb99a-1870-4f55-8759-dd584192d840" width=300/> | <image src="https://github.com/user-attachments/assets/f87ab717-94e7-4a87-a80d-87581a342cd5" width=300/> | <image src="https://github.com/user-attachments/assets/e9b0ede3-b3e8-40d3-a04d-9cc9a40b3289" width=300/> |

## To Reviewers
- 작업을 하다보니 코드량이 너무 길어져서ㅠㅠ 중간에 끊었다가 갈게요..!
- 아직 UI가 완전히 나온 게 아니라서 나온 부분만 구현했어요
- 각 화면마다 여러 UI 케이스들이 있는데 이건 서버통신 연동하면서 더 구현할게요!

2024-12-25 15:30 UTC, l2hyunwoo commented on app/build.gradle.kts
> +    implementation(libs.compose.ui.tooling)
이거 debugImplementation으로 추가해주시면 좋을 것 같아요

https://developer.android.com/develop/ui/compose/setup

2024-12-25 15:31 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/auth/AuthActivity.kt
오 애니메이션 잘 구현했네요?!! 대박

2024-12-25 15:35 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/auth/AuthActivity.kt
> +                val action by viewModel.action.collectAsStateWithLifecycle()
이건 ViewModel의 변수명을 조금 더 구체적으로 작성하면 좋을 것 같아요. 리뷰할 때 어떤 액션인지 잘 몰랐어서 ViewModel 봐서 역할 이해할 수 있었어요..!!

2024-12-25 15:39 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/auth/AuthActivity.kt
> +                            }
lifecycleScope이 위에서 선언이 안되어있는 것 같은데 혹시 컴파일 에러 나지 않았나요....?

2024-12-25 15:41 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/auth/AuthActivity.kt
> +                onClick = {},
// TODO SOPT 회원가입 기능 구현 by yubinlee

2024-12-25 15:42 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/auth/AuthActivity.kt
> +                thickness = 0.6.dp,
```suggestion
                thickness = Dp.Hairline,
```

이건 어떨까요?

2024-12-25 15:42 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/auth/AuthActivity.kt
> +                thickness = 0.6.dp,
여기도 마찬가지

2024-12-25 15:43 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/auth/AuthViewModel.kt
> +    val action: StateFlow<Boolean?> = _action.asStateFlow()
혹시 이건 StateFlow로 구현한 이유가 있을까요? 이건 이벤트쪽인 것 같아서 State보단 Shared로 구현하는게 더 자연스러울 것 같아서요...!!

2024-12-25 15:44 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/auth/component/AuthButton.kt
> +    paddingHorizontal: Dp = 0.dp,
`paddingVertical`, `paddingHorizontal` 을 합쳐서

```kotlin
    padding: PaddingValues
```

로 합치면 어떨까요?

2024-12-25 15:45 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/auth/component/AuthTextField.kt
> +                )
```suggestion
            if (text.isEmpty()) {
                Text(
                    text = hintText,
                    color = Gray100,
                    style = SoptTheme.typography.body14M
                )
            }
```

2024-12-25 15:49 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/auth/component/AuthTextField.kt
> +    hintText: String,
https://m3.material.io/components/text-fields/guidelines

labelText(or placeHolder)라는 네이밍은 어떨까요? Material3 보니까 기본 placeHolder가 labelText로 되어있네요

2024-12-25 15:55 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/auth/component/LoginErrorDialog.kt
> +            }
이거 noClickable 인 것 같은데 사용자가 이 버튼을 눌렀다는 시각적 효과를 주기 위해서 기본적으로 리플 주는 게 좋을 것 같아요...!!

2024-12-25 15:55 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/auth/component/PhoneCertification.kt
> +}
👍🏻

2024-12-25 15:57 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/auth/feature/certificatemember/CertificateMemberScreen.kt
> +    )
👍🏻

2024-12-25 15:58 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/auth/feature/certificatemember/CertificateMemberScreen.kt
> +    }
```suggestion
    val onShowSnackBar: () -> Unit = remember { {
        coroutineScope.launch {
            snackBarHostState.showSnackbar("인증번호가 전송되었어요.")
        }
    } }
```

(혹시 모르는데) 이 함수가 리컴포지션될때마다 매번 리컴포지션 범위에 포함되어서 다시 함수객체가 만들어질 수 있으니 remember로 감싸주면 좋을 것 같아요

2024-12-25 15:59 UTC, l2hyunwoo requested changes
고생하셨어요 🙇🏻  리뷰 남겼습니다

2024-12-30 13:33 UTC, leeeyubin commented on app/src/main/java/org/sopt/official/feature/auth/AuthActivity.kt
> +                            }
`androidx.lifecycle.lifecycleScope`를 임포트 해놔서 컴파일 에러가 안 나는 것 같습니다..!

2024-12-30 16:31 UTC, leeeyubin commented
코드리뷰 반영했습니다! 확인부탁드려요! @l2hyunwoo

2024-12-30 18:13 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/auth/component/LoginErrorDialog.kt
> +            }
설명 감사합니다.

2024-12-30 18:21 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/auth/AuthViewModel.kt
> +    val action: StateFlow<Boolean?> = _action.asStateFlow()
아 그런 요구사항이 있었구만유, 그런 경우에는 action이란 표현 대신에 isLoginErrorPopupVisible 정도로 축약해도 좋을 것 같아요. 아니면, 이건 UI단에서만 알고 있어도 되는 정보이니, setContent안에

```kotlin
  var isErrorDialogVisible by remember { mutableStateOf(false) }
```

로 사용해도 괜찮을듯합니다! 상태값 업데이트 코드는 AuthUiEvent가 Failure일 때 LaunchedEffect에서 작성하면 될 것 같구요

2024-12-30 18:25 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/auth/AuthActivity.kt
> +                }
토큰 있는 경우에는 어떻게 동작하나요...?

2024-12-30 18:27 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/auth/AuthActivity.kt
> +                val action by viewModel.loginDialogAction.collectAsStateWithLifecycle()
1.
```suggestion
                val loginDialogAction by viewModel.loginDialogAction.collectAsStateWithLifecycle()
```

2. 저게 액션일까요?
3. collectAsStateWithLifecycle이 필요할까?
4. ViewModel에 변수로 선언해야하는가?

2024-12-30 18:34 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/auth/AuthActivity.kt
> +                        (getSystemService(NOTIFICATION_SERVICE) as NotificationManager).createNotificationChannel(this)
```suggestion
                        getSystemService<NotificationManager>.createNotificationChannel(this)
```

2024-12-30 18:35 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/auth/AuthActivity.kt
> +                            }
오래된 잔재....이건 제가 건드려야될 것 같군요 ㅠ

2024-12-30 18:40 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/auth/component/AuthButton.kt
> +    disabledContentColor: Color = Gray60,
```suggestion
    isEnabled: Boolean = true,
    containerColor: Color = White,
    contentColor: Color = Black,
    disabledContainerColor: Color = Black80,
    disabledContentColor: Color = Gray60,
```

~Defaults object를 활용해서 컬러 시스템을 하나의 객체 안에서 관리할 수 있게하는 패턴이 있습니당!

2024-12-30 18:42 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/auth/component/AuthButton.kt
> +    disabledContentColor: Color = Gray60,
https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/material/material/src/commonMain/kotlin/androidx/compose/material/TextFieldDefaults.kt?q=TextFieldDefaults

나중에 이거 참고해서 리팩토링해도 괜찮을 듯 (우선순위 하~최하)

2024-12-30 18:49 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/auth/component/LoginErrorDialog.kt
> +    val backgroundColor = if (isPressed) Gray700 else Gray800
```suggestion
    val backgroundColor = remember(isPressed) { if (isPressed) Gray700 else Gray800 }
```

2024-12-30 18:52 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/auth/feature/certificatemember/CertificateMemberScreen.kt
> +                ),
background나 clip도 같이 shape 잡아주는게 좋습니다...!!!

2024-12-30 19:05 UTC, l2hyunwoo approved these changes

2024-12-30 19:35 UTC, merged