feat: 운영서비스 - 출석 점수 조회 기능 구현
sopt-makers/sopt-android pull request #139
Opened 2023-04-02 09:31 UTC by hansh0101

## What is this issue?
- [ ] #138 
![image](https://user-images.githubusercontent.com/81508084/229344583-eab6dd24-6dd4-4d61-bbba-c8132e9c5457.png)

## Log
- 다 완성하고 PR 날리면 읽기 힘들 것 같아 조금씩 추가하겠습니다. :-)
- 0402: 레이아웃 완성(UI 구조 부분 및 변경된 파일 참고해주시면 감사하겠습니다.)

## UI 구조
- makers 노션 페이지 내 `운영 프로덕트 팀 / 안드로이드 / SPR1 - 출석 점수 조회`를 참고하면 View 설계 의도를 이해하는 데 더욱 도움이 될 수 있습니다. (크롬 시크릿 모드로 노션 링크를 접속해봤을 때 들어가지는 것으로 확인되어 별도 링크를 첨부하지 않습니다.)
- 앱바, 행사 정보 영역은 고정 영역이고 출석 히스토리 영역은 스크롤 영역입니다.
- 상단 앱바는 Toolbar를 활용해 구현하였습니다.
- 행사 정보 영역은 하나의 ConstraintLayout 내에 여러 컴포넌트를 배치했습니다. 이는 출석 조회 기능 이후 출석 기능을 구현할 때 하단에 1차 출석, 2차 출석, 출석 완료라는 3개의 상태를 가진 Progress View를 추가해야 하는데 이 때 이 Progress View를 ConstraintLayout 안에 추가로 구현하기만 하면 편리할 것이라 판단했습니다.
- 출석 히스토리 영역은 RecyclerView Multi ViewType을 활용합니다. ScrollView 안에 출석 점수 현황 / 출석 로그를 보여주는 방향도 고려했으나, ViewHolder 재사용 및, 현재(2기) 운영서비스 팀은 출석 히스토리가 많아야 10여개 정도로 예상하고 있지만, 이후 기수에서 더욱 다양하게 히스토리를 보여줄 경우를 고려했습니다.

2023-04-02 09:40 UTC, l2hyunwoo requested changes
의견 남겼습니다. 한번 확인해주세요!

2023-04-02 09:40 UTC, l2hyunwoo commented on app/build.gradle.kts
> +    id("org.jetbrains.kotlin.android")
이거 이미 위의 application 플러그인에 다 들어가있으니 삭제 ㄱ

2023-04-02 09:40 UTC, l2hyunwoo commented on app/build.gradle.kts
> +    implementation("androidx.appcompat:appcompat:1.4.1")
이것도 플러그인에 다 기본 내장되어있을겁니다

2023-04-02 09:40 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/attendance/AttendanceActivity.kt
> +        binding = DataBindingUtil.setContentView(this, R.layout.activity_attendance)
데이터 바인딩 안 쓰면 굳이 데이터바인딩보단 뷰비인딩 쓰면 좋을 것 같아요. 불필요한 빌드타임 증기를 야기힙니다

2023-04-02 09:40 UTC, l2hyunwoo commented on app/src/main/res/layout/activity_attendance.xml
> +            android:backgroundTint="#2C2D2E"
이거 제가 나중에 디자인 시스템 만들때 같이 변경하면 좋을 듯

2023-04-02 09:40 UTC, l2hyunwoo commented on app/src/main/res/layout/item_attendance_history_log_header.xml
> +        android:textSize="14dp"
textSize 확대했을 때 깨져도 dp보단 sp 적용하는게 좋을 것 같습니다. 시력 안좋은 친구들도 좀 텍스트 키워서 사용할 수도 있으니까(아님 원시여서 작게 쓸 수도…?)

2023-04-02 09:41 UTC, l2hyunwoo commented
그리고 아직 작업 남아있으면 PR Draft로 변경해주시먄 좋을 것 같네요

2023-04-02 09:42 UTC, hansh0101 commented on app/src/main/res/layout/activity_attendance.xml
> +            android:backgroundTint="#2C2D2E"
이 부분은 지금 가볍게 만들고 있는 부분이고 안드로이드 팀원 분들과 이야기를 한 후에 해야할 것 같아서, 직접 디자인 시스템을 건들기보다는 제가 임의로 넣은 의도였습니다. 디자인 시스템 정립되면 바로 변경하도록 하겠습니다.

2023-04-02 09:42 UTC, hansh0101 commented on app/src/main/res/layout/item_attendance_history_log_header.xml
> +        android:textSize="14dp"
운영서비스 팀원들에게 의견 전달해보도록 하겠습니다.

2023-04-02 09:44 UTC, l2hyunwoo commented on app/src/main/res/layout/activity_attendance.xml
> +            android:backgroundTint="#2C2D2E"
네 빠르게 작업하도록 하겠습니다

2023-04-02 09:46 UTC, l2hyunwoo commented on app/src/main/res/layout/item_attendance_history_log_header.xml
> +        android:textSize="14dp"
네 좋습니다. 그런데 이것도 아마 제가 테마로 정의할 것 같이서 그거 그대로 가져다 쓰면될듯

2023-04-03 09:53 UTC, hansh0101 commented on app/src/main/res/layout/item_attendance_history_log_header.xml
> +        android:textSize="14dp"
Good

2023-04-06 07:20 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/di/attendance/AttendanceBindsModule.kt
> +}
굳이 모듈 두개로 안나눠도 하나에서 다 선언할 수 있습니다. 아래 코드로 테스트 해봤는데 무리 없이 앱 실행되는 것 확인했습니다.

```suggestion
@Module
@InstallIn(SingletonComponent::class)
abstract class AttendanceModule {
    @Binds
    @Singleton
    abstract fun bindAttendanceRepository(
        attendanceRepositoryImpl: AttendanceRepositoryImpl
    ): AttendanceRepository

    companion object {
        @Provides
        @Singleton
        fun provideAttendanceService(): AttendanceService = MockAttendanceService()
    }
}
```

2023-04-06 08:08 UTC, hansh0101 commented on app/src/main/java/org/sopt/official/di/attendance/AttendanceBindsModule.kt
> +}
확인 후 적용해보겠습니다. :-)

2023-04-08 09:13 UTC, miinjung commented on app/src/main/res/layout/activity_attendance.xml
> +        android:background="#0F1010">
색상은 raw 값 말고, 값을 정의해서 넣어보면 어떨까요?

2023-04-08 09:13 UTC, miinjung commented on app/src/main/res/layout/activity_attendance.xml
> +            android:layout_marginHorizontal="20dp"
marginHorizontal 은 API 26 이상 부터 사용할 수 있는 것으로 알고 있어서인데, 우리 min 28이구나... ㅋㅋㅋㅋㅋ 참고용으로만 남겨놓을게요

2023-04-08 09:13 UTC, miinjung commented on app/src/main/res/layout/item_attendance_history_summary.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
의미없는 빈줄들은 제거하는건 어떨까용???

2023-04-08 09:13 UTC, miinjung commented on app/src/main/res/values/colors.xml
> +    <color name="purple_40">#C6A9FF</color>
위와 같이 주석과 함께 컬러값넣어주세요. 디자인 시스템에 예외적으로 적용되는 색상이라면 해당 부분은 디자인 시스템에 필요없는지도 한번 문의주심 감사하겠습니다.

2023-04-08 09:16 UTC, l2hyunwoo commented on app/src/main/res/layout/activity_attendance.xml
> +            android:layout_marginHorizontal="20dp"
@miinjung min 30으로 올릴까?ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2023-04-08 09:17 UTC, l2hyunwoo commented on app/src/main/res/layout/activity_attendance.xml
> +        android:background="#0F1010">
@miinjung 이거..진짜 작업 오늘 이내로 해볼게요 ㅠㅠ 디자인 시스템 작업때문에 raw값 사용할 수 밖에 없는 상황입니다.

2023-04-08 09:18 UTC, hansh0101 commented on app/src/main/res/layout/item_attendance_history_summary.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
저는 개인적으로 이게 구분하기 편해서 그렇긴 한데 ... 팀적으로 의미없는 빈 줄이 없는게 좋다면 고려해볼게요 !

2023-04-08 09:21 UTC, hansh0101 commented on app/src/main/res/layout/activity_attendance.xml
> +        android:background="#0F1010">
색상 작업을 제가 할까도 했는데 앱 팀 + 운영서비스 팀 둘 다 사용하게 될 것 같아 제가 임의로 건들기가 그렇더라구요. 이 부분 염두에 두고 있고 디자인 시스템이 정의되면 싹 고쳐넣도록 할게요 !

2023-04-08 09:52 UTC, miinjung commented on app/src/main/res/layout/activity_attendance.xml
> +            android:layout_marginHorizontal="20dp"
음.... 28정도면 괜찮지 않을까? 그냥 다른 앱에서 min이 26 이하인 케이스가 있을 수 있으니 참고사항으로 남겨놨습니다. 회사에서도 잘못 사용했다가 적용안되는걸 확인한 적이 있었어서

2023-04-08 09:52 UTC, miinjung commented on app/src/main/res/layout/activity_attendance.xml
> +            android:layout_marginHorizontal="20dp"
@l2hyunwoo 우리 아직 데이터 없지? 버전 어떤거 많이 사용하는지. 나중에 수집한 이후에 min 올리는거 검토해보자

2023-04-08 09:53 UTC, miinjung commented on app/src/main/res/layout/activity_attendance.xml
> +        android:background="#0F1010">
아항 그런 히스토리가 있었군요 오케이.... 일단 raw로 넣고 한번에 얼라인 하는걸로 알고 있을게요

2023-04-08 09:53 UTC, miinjung commented on app/src/main/res/layout/activity_attendance.xml
> +        android:background="#0F1010">
@l2hyunwoo 아니면 이번 스프린트까지 그냥 raw 쓰고 한번에 싹 업데이트 하는 PR 올릴까?

2023-04-08 09:54 UTC, l2hyunwoo commented on app/src/main/res/layout/activity_attendance.xml
> +            android:layout_marginHorizontal="20dp"
@miinjung 어 아직은 없어 근데 안드로이드 기종 특성상 20대 초중반 친구들이 과연 성능 안좋은 + 오래된 26버전 안드폰을 쓸까라는 생각이 들긴 해서. 30은 나도 좀 과격하다고 생각하긴해

2023-04-08 17:24 UTC, l2hyunwoo requested changes
음 이번 커밋은 원복시키는 것을 권장합니다....디자인이 깨지더라도 접근성을 높여서 사용성에 해를 끼치게 하지 않는 것이 모든 사람들이 편하게 사용할 수 있는 서비스의 메이커가 가져야 할 생각 중 하나라고 생각합니다.

디자인 측에서 dp 고정 관련 이야기가 먼저 나온 것이더라도 이런 부분은 개발자 측에서 설득을 할 수 있는 부분이라고 생각합니다.

2023-04-08 17:24 UTC, l2hyunwoo commented on app/src/main/res/layout/activity_attendance.xml
> +                    android:textSize="14dp"
sp를 활용해주시는 것을 권장드립니다....

2023-04-09 06:28 UTC, l2hyunwoo commented on app/src/main/res/layout/activity_attendance.xml
> +        android:background="#0F1010">
@miinjung #147 이거 올려뒀습니당..!! 이 PR 머지 이후에 싹 다 바꿀거에요

2023-04-09 07:47 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/data/model/attendance/AttendanceHistoryResponse.kt
> +) {
이 부분 release 빌드에서 변수명 난독화되어서 제대로 안받아와질 수도 있어요. 웬만하면 @SerialName 어노테이션 다 붙여주세요

2023-04-09 08:08 UTC, hansh0101 commented on app/src/main/java/org/sopt/official/data/model/attendance/AttendanceHistoryResponse.kt
> +) {
넵

2023-04-11 10:43 UTC, miinjung commented
drawable 은 radius 에 따라서 네이밍 하고 그거 재활용하면 될라나?

2023-04-11 11:34 UTC, l2hyunwoo commented
> drawable 은 radius 에 따라서 네이밍 하고 그거 재활용하면 될라나?

이거 shape_{color}_{radius} 는 어떄? @hansh0101 @miinjung @hjh1161514

2023-04-11 11:36 UTC, miinjung commented
컬러는 backgroundTint 로! 색상까지 넣으면 확장성 떨어지니깐 (컬러 switching 할수도 있고, 컬러 tint 로 먹이면 더 적은 drawable로 할 수 있으니깐!)

2023-04-11 14:06 UTC, hansh0101 commented
> > drawable 은 radius 에 따라서 네이밍 하고 그거 재활용하면 될라나?
> 
> 이거 shape_{color}_{radius} 는 어떄? @hansh0101 @miinjung @hjh1161514

나도 이거 컬러 넣을지 생각해봤는데 radius 값은 같은데 색만 다른 게 여러 개 생길 것 같다는 생각도 들어서 그냥 색상은 안 넣었어

2023-04-13 04:36 UTC, hjh1161514 commented
AttendanceActivity.kt에서 `updateSoptEventComponentWithNoSession`, `updateSoptEventComponentWithHasAttendance`, `updateSoptEventComponentWithNoAttendance`에 공통적으로 들어간 부분을 빼면 어떨까 생각도 했는데 가독성을 생각하면 
지금 코드가 더 좋을 것 같네요. 이 외에는 리뷰를 남길 부분이 없습니다. 수고하셨습니다👍👍

2023-04-13 04:38 UTC, hjh1161514 approved these changes
AttendanceActivity.kt에서 `updateSoptEventComponentWithNoSession`, `updateSoptEventComponentWithHasAttendance`, `updateSoptEventComponentWithNoAttendance`에 공통적으로 들어간 부분을 빼면 어떨까 생각도 했는데 가독성을 생각하면 
지금 코드가 더 좋을 것 같네요. 이 외에는 리뷰를 남길 부분이 없습니다. 수고하셨습니다👍👍

2023-04-13 04:40 UTC, l2hyunwoo approved these changes
고생하셨습니다.

2023-04-13 04:40 UTC, l2hyunwoo commented on app/src/main/res/values/themes.xml
> +    </style>
이 부분 디자인 시스템에 있는 색상 맞춰서

2023-04-14 01:43 UTC, hansh0101 commented
> AttendanceActivity.kt에서 `updateSoptEventComponentWithNoSession`, `updateSoptEventComponentWithHasAttendance`, `updateSoptEventComponentWithNoAttendance`에 공통적으로 들어간 부분을 빼면 어떨까 생각도 했는데 가독성을 생각하면 지금 코드가 더 좋을 것 같네요. 이 외에는 리뷰를 남길 부분이 없습니다. 수고하셨습니다👍👍

이 부분 공통적인 부분 빼낼까 고민도 했는데 저 3개 상황이 딱딱 나뉘고 이후에 저 3개 상황 각각에 맞춰서 ... UI가 변하기 때문에 일단은 공통 로직을 빼는 것보다 상황 분리에 조금 더 맞춰서 짰습니다 ... !

2023-04-14 08:05 UTC, l2hyunwoo commented on app/src/main/res/values/themes.xml
> +        <item name="android:statusBarColor">@color/black_100</item>
이거 이미 Theme.SOPT에서 ``?android:colorBackground``로 설정해놔서 의미 없을 것 같아. 이거 지우고 AttendanceActivity도 Theme.SOPT 상속받게 해도 괜찮을듯

2023-04-14 09:47 UTC, merged