[김다혜] Pair, Triple -> Data Class 전환
sopt-makers/sopt-android pull request #326
Opened 2023-09-07 08:56 UTC by kimdahyee

## What is this issue?
- Pair, Tirple을 각각에 맞는 Data Class로 전환

## Reference

2023-09-07 13:18 UTC, l2hyunwoo requested changes
gitignore 쪽 표기/MainUrl 네이밍 논의 차원에서 Request Changes 부여했습니다. 확인 부탁드려요

2023-09-07 13:18 UTC, l2hyunwoo commented on .gitignore
> -google-services.json
`app/` 표기는 필요 없을 것 같아요! 혹시 붙이신 이유가 있을까요?

2023-09-07 13:18 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/domain/entity/main/MainView.kt
> +)
urlN 타입의 변수명은 구분 짓기 힘든 것 같아요...

leftBlockUrl, rightTopBlockUrl, rightBottomBlockUrl 정도는 어떨까요?

2023-09-07 13:18 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/domain/entity/main/MainView.kt
> +)
`UserActiveGeneration` 정도의 이름은 어떠신가요? (활동기수)

2023-09-07 13:18 UTC, l2hyunwoo commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/model/RankerModel.kt
> +)
RankersUiModel의 네이밍이 더 좋을 것 같습니다. 

컴포즈 모듈쪽에서는 UiModel이 컨벤션으로 정해진 suffix여서요!!

2023-09-07 13:19 UTC, l2hyunwoo commented
그리고 PR 빌더는 봇때문에 실패난거니 걱정 ㄴㄴ

2023-09-10 10:21 UTC, kimdahyee commented on app/src/main/java/org/sopt/official/domain/entity/main/MainView.kt
> +)
UserActiveGeneration(활동기수)의 경우 "UserState.Active"의 의미와 중복되게 느껴질 수 있을거 같아요
기수 정보의 의미로 GenerationInfo라 정해보았는데 혹시 다른 아이디어가 있을까요 ?

2023-09-10 10:21 UTC, kimdahyee commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/model/RankerModel.kt
> +)
넵 !!

2023-09-10 10:22 UTC, kimdahyee commented on .gitignore
> -google-services.json
아니요 .. 파일 수정하면서 의도치 않은 변경이 있었던거 같아요 !
다시 수정했습니다

2023-09-10 10:22 UTC, kimdahyee commented on app/src/main/java/org/sopt/official/domain/entity/main/MainView.kt
> +)
비슷한 느낌으로 수정했습니다 ~~~

2023-09-10 10:28 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/domain/entity/main/MainView.kt
> +)
우선 State라는 suffix에서 상태라는걸 파악할 수 있어서 크게 중복되게 느껴지지 않는다고 생각합니다... 그리고 Info라는 suffix는 굉장히 모호한 의미를 가지고 있어서(data, info 등) 지양을 하는게 좋을 것 같아요!

2023-09-10 10:29 UTC, l2hyunwoo approved these changes
리뷰 한개만 확인해주시고 수정 필요하다면 수정한 다음 머지해주시면 되겠습니다. 고생하셨습니다 👍🏻

2023-09-10 10:29 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/domain/entity/main/MainView.kt
> +)
굳!

2023-09-10 12:18 UTC, merged