메인 - 보라색 걷어내기
sopt-makers/sopt-android pull request #344
Opened 2023-09-18 08:21 UTC by kimdahyee

2023-09-19 13:26 UTC, l2hyunwoo requested changes
고생했습니다. 리뷰 확인해주세용

2023-09-19 13:26 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/main/MainViewModel.kt
> +import android.util.Log
이거 왜 있을까요?

2023-09-19 13:26 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/main/MainActivity.kt
> +import android.util.Log
이런게 왜 있죠?

2023-09-19 13:26 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/main/MainActivity.kt
> +import android.util.Log
+) Timber.d 쓰시는게 경고가 안뜹니다.

2023-09-19 13:26 UTC, l2hyunwoo commented on app/src/main/res/layout/activity_sign_out.xml
> -    <Button
요기도

2023-09-19 21:49 UTC, l2hyunwoo approved these changes
추가 코멘트 하나만 확인해주고 머지드갑시다

2023-09-19 21:49 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/main/MainViewModel.kt
> +                        description.value = it.asNullableWrapper()
asNullableWrapper 빼줘도 될 것 같아!

2023-09-20 03:12 UTC, hjh1161514 commented
코드 모두 확인했는데 먼저 머지해도 문제 없을 것 같아 진행하도록 하겠습니다!

2023-09-20 09:38 UTC, merged