Refactor/#416 core network
sopt-makers/sopt-android pull request #423
Opened 2023-11-01 08:25 UTC by lsakee

## What is this issue?
- #416 core network 모듈제작

## Reference
- [x]

## point
- authenticator / intercept network 모듈로 이전하였습니다.
- authservice에서 refresh api network 모듈로 이전하였습니다.
- datastore도 network 모듈로 이동하였습니다.
- di ( AuthModule 일부 , NetModule , SecurityModule ) network 모듈로 이동하였습니다.
- flipper 릴리즈/디버그 모드로 이동하였습니다.

2023-11-05 09:34 UTC, l2hyunwoo requested changes
고생하셨습니다. 리뷰가 늦어졌는데 제가 현생에서 갈리느라 그런것이라 양해부탁드릴게요. 코드 전반적으로 Core-network에 들어갈만한 코드인지 아닌지 더 고민해봐야할 코드가 있는 것 같아서 같이 의견 나눠보시면서 개발 진행방향 잡아나가면 좋을 것 같습니다 👍🏻

2023-11-05 09:34 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/App.kt
> +        FlipperInitializer
```suggestion
        FlipperInitializer.init(this)
```

기존 코드 그대로 가져가야되지 않을까요?

2023-11-05 09:34 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/data/mapper/AuthResponseMapper.kt
> +fun toAuthResponse(responseItem: AuthResponse): org.sopt.official.data.model.response.AuthResponse {
- `org.sopt.official.data.model.response.` 길이가 길어서 불필요한 prefix인 것 같은데 어떻게 생각하시나요?
- 현재 코드 기준으로 다른 매퍼 함수들은 확장함수의 형태로 매퍼를 정의하고 있습니다. 코드의 통일성을 주기 위해 해당 형태로 변경해주실 것을 부탁드립니다.
- 두 모듈 모두 동일한 리스폰스를 사용한다면 data 모듈에서 core-network를 참조하고 data 모듈에서 core-network의 AuthResponse를 참조하는 것도 괜찮겠다 생각이 드네요. 그러면 이런 매퍼 함수도 필요없을 것 같습니다.

2023-11-05 09:34 UTC, l2hyunwoo commented on core/network/src/main/java/org/sopt/official/network/service/AuthService.kt
> +interface AuthService {
refresh 함수만 들어있으면 RefreshService로 바꿔도 좋을 것 같네요

2023-11-05 09:34 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/data/source/impl/DefaultRemoteAuthDataSource.kt
> +    @Auth(false) private val noneAuthService: org.sopt.official.network.service.AuthService,
그러면 이런 불필요한 prefix도 없애도 될 것 같구요

2023-11-05 09:34 UTC, l2hyunwoo commented on core/network/src/main/java/org/sopt/official/network/authenticator/SoptAuthenticator.kt
> +interface ProvidesIntents {
- 다른 파일로 분리해주시면 좋을 것 같습니다.
- core/network 모듈과는 다른 모듈에서 사용되면 좋을 것 같네요. network 모듈이 가져가야할 책임은 아닌 것 같습니다.
- 더 추상화된 역할로는 Navigator라는 네이밍으로 가져가면 좋을 것 같습니다.

2023-11-05 09:34 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/auth/ProvidesIntent.kt
> +}
위의 리뷰 참고해주세요

2023-11-05 09:34 UTC, l2hyunwoo commented on core/network/src/androidTest/java/org/sopt/official/network/ExampleInstrumentedTest.kt
불필요한 파일 삭제 부탁드립니다.

2023-11-05 09:34 UTC, l2hyunwoo commented on core/network/proguard-rules.pro
불필요한 파일 삭제 부탁드립니다.

2023-11-05 09:34 UTC, l2hyunwoo commented on core/network/src/main/java/org/sopt/official/network/model/response/AuthResponse.kt
위의 리뷰 참고해주세요

2023-11-05 09:34 UTC, l2hyunwoo commented on core/network/src/test/java/org/sopt/official/network/ExampleUnitTest.kt
불필요한 파일 삭제부탁드립니다.

2023-11-06 15:06 UTC, lsakee commented on app/src/main/java/org/sopt/official/App.kt
> +        FlipperInitializer
넵! 수정하겠습니다.

2023-11-06 15:07 UTC, lsakee commented on core/network/src/main/java/org/sopt/official/network/service/AuthService.kt
> +interface AuthService {
불필요한 prefix를 생각하지 못하였네요

2023-11-06 15:08 UTC, lsakee commented on core/network/src/main/java/org/sopt/official/network/authenticator/SoptAuthenticator.kt
> +interface ProvidesIntents {
네이밍의 역할과 network모듈에서 책임지는 방법이 아닌 다른 방법으로 적용해서 pr올리겠습니다!

2023-11-07 01:57 UTC, l2hyunwoo requested changes
다시한번 리뷰 확인해주세요 :) 고생하셨습니다.

2023-11-07 01:57 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/data/mapper/AuthMapper.kt
> +}
Mapper를 따로 클래스로 구현하는 이유가 있나요? 클래스로 매퍼를 구현했을 때의 이점을 공유해주시면 감사하겠습니다.

2023-11-07 01:57 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/data/source/impl/DefaultRemoteAuthDataSource.kt
> +    @Auth(false) private val noneRefreshService: RefreshService,
이렇게 Service를 구분할 수 있으면 어노테이션을 굳이 붙혀서 구분하지 않아도 되겠죠?

2023-11-07 01:57 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/data/source/impl/DefaultRemoteAuthDataSource.kt
> +    @Auth(false) private val noneRefreshService: RefreshService,
그리고 패러미터 이름도 변경되면 좋을 것 같네요

2023-11-07 01:57 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/di/NavigatorModule.kt
> +}
동사형보다 명사형으로 클래스명 적으면 좋을 것 같네요

2023-11-07 01:57 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/navigator/NavigatorProvidesIntent.kt
> +
빈줄!

2023-11-07 01:57 UTC, l2hyunwoo commented on core/network/src/main/java/org/sopt/official/network/authenticator/SoptAuthenticator.kt
> +    @Auth(false) private val service: RefreshService,
이것도 어노테이션 떼면 될 것 같구요

2023-11-07 01:57 UTC, l2hyunwoo commented on settings.gradle.kts
>  include(":domain:soptamp")
이것도 위의 형식처럼 하나로 묶어주세요

2023-11-07 02:56 UTC, lsakee commented on app/src/main/java/org/sopt/official/data/mapper/AuthMapper.kt
> +}
가독성이 더 좋다고 생각합니다 그리고 기존의 mapper와 통일성을 가져갔습니다!

2023-11-07 05:08 UTC, l2hyunwoo reviewed
고생하셨습니다 :) 리뷰 반영해주시고 마지막에

```
./gradlew spotlessApply
```

한번만 터미널에서 실행해주시겠어요?

2023-11-07 05:08 UTC, l2hyunwoo commented on core/network/src/main/java/org/sopt/official/network/service/RefreshService.kt
> +
빈칸!

2023-11-07 05:41 UTC, l2hyunwoo approved these changes
LGTM 👍🏻

2023-11-07 06:01 UTC, merged

2023-11-07 06:08 UTC, l2hyunwoo commented
@allcontributors please add @lsakee for code