Baseline Profiles 탑재 작업
sopt-makers/sopt-android pull request #453
Opened 2023-11-15 07:47 UTC by KwakEuiJin

## What is this issue?
close #449

## Reference
### 테스트 결과
테스트 모수를 20으로 임의적으로 늘렸습니다.

None Compile : 370.7ms
Full Complie: 397.3ms
BaseLineProfiles Compile: 378.8ms

공식문서는 벤치마크 결과는 [컴파일 없음(324ms), 전체 컴파일(315ms), 부분 컴파일(312ms) 및 기준 프로필(229ms)] 이던데 왜 제 결과와 다른지 조금 의문이네요

```
StartupBenchmarks_startupCompilationBaselineProfiles
timeToInitialDisplayMs   min 335.8,   median 378.8,   max 441.4
Traces: Iteration 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
Timed out waiting for process (org.sopt.official) to appear on samsung-sm_s916n-R3CW702RN8X.
StartupBenchmarks_startupCompilationFull
timeToInitialDisplayMs   min 367.8,   median 397.3,   max 449.1
Traces: Iteration 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
StartupBenchmarks_startupCompilationNone
timeToInitialDisplayMs   min 354.0,   median 370.7,   max 448.5
Traces: Iteration 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
```

## 테스트 인증샷
<img width="1677" alt="image" src="https://github.com/sopt-makers/sopt-android/assets/93872496/25418f5c-dcaa-4dc6-b9c2-bb293201ebf5">

2023-11-15 07:57 UTC, l2hyunwoo requested changes
리뷰 참고해주세요! 고생많았습니다.

2023-11-15 07:57 UTC, l2hyunwoo commented on benchmark/src/main/java/org/sopt/official/benchmark/BaselineProfileGenerator.kt
> +        rule.collect("org.sopt.official") {
패키지 네임 상수로 바꿔주세요!

2023-11-15 07:57 UTC, l2hyunwoo commented on benchmark/src/main/java/org/sopt/official/benchmark/StartupBenchmarks.kt
지금 테스트가 Cold start에서만 돌고 있는 것 같은데, Warm과 Hot일 때도 어떻게 도는지 보면 좋을 것 같아요

2023-11-15 11:18 UTC, KwakEuiJin commented
@l2hyunwoo  위 코멘트 수정 및 셋팅 추가했습니다 🙏
테스트 결과는 description에 update해두었습니다!
확인해주시면 감사하겠습니다~!!

2024-05-26 06:31 UTC, l2hyunwoo approved these changes
👍🏻 고생하셨습니다 @KwakEuiJin

2024-05-26 06:32 UTC, merged