[feature/soptamp part ranking] Server 제외 구현 완료
sopt-makers/sopt-android pull request #642
Opened 2024-03-28 08:14 UTC by chattymin

closed #637 
## What is this issue?
- [x] 파트별 랭킹 UI 구현
- [x] 페이지 이동 연결 

## To Reviewer
통짜 PR 죄송합니다... 하다가 잘 되길래 신나서 많이 해버렸어요...

2024-03-28 08:18 UTC, giovannijunseokim commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/RankColor.kt
> +    else -> Gray400
요 색은 SoptTheme에 저장이 안 되어있나요 !?

2024-03-28 08:19 UTC, giovannijunseokim commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/RankingBar.kt
> +            .size(width, height)
width와 height를 받는 것과 modifier 인자를 받는 것 중 이렇게 선택하신 이유가 궁금합니다 !

2024-03-28 08:20 UTC, giovannijunseokim commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/TopRankerItem.kt
> +        RankingBar(90.dp, height, ranker.rank) {
인자명을 명시해주면 가독성이 더 좋을 것 같은데 어떻게 생각하시나요 !?

2024-03-28 08:22 UTC, giovannijunseokim commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/part/PartRankingScreen.kt
> +fun PartRankingScreen(
메서드 오버로딩을 사용한 기법인가요?? 신박한데요 ㄷㄷ

2024-03-28 08:22 UTC, giovannijunseokim commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/part/PartRankingScreen.kt
> +    refreshing: Boolean = false,
Boolean이니 변수명을 isRefreshing으로 바꾸는 것도 좋아보입니다!

2024-03-28 08:41 UTC, giovannijunseokim approved these changes
고생하셨습니다 ~!!! 👍👍👍👍

2024-03-28 08:47 UTC, l2hyunwoo requested changes
다시 한번 보시면 좋겠습니다.

+ spotlessApply 돌리세요

2024-03-28 08:47 UTC, l2hyunwoo commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/list/MissionListScreen.kt
>      menuTexts: List<String>,
이거 List type으로 되어있네...이거 kotlinx-immutable-collection 라이브러리 써서 ImmtableList<String>으로 바꿔주실 수 있겠어요?

2024-03-28 08:47 UTC, l2hyunwoo commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/RankColor.kt
> +    else -> Gray400
SoptTheme.colors.onSurface40 쓰면 됩니다.

2024-03-28 08:47 UTC, l2hyunwoo commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/RankColor.kt
> +    else -> Gray300
이 친구도

2024-03-28 08:47 UTC, l2hyunwoo commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/RankingBar.kt
> +fun RankingBar(width: Dp, height: Dp, rank: Int, content: @Composable () -> Unit = {}) {
하하 이건....Modifier에서 사용할 수 있는 속성들은 최대한 Modifier를 통해서 받아오라는 글이 있었는데, 찾아보려니까 찾기 힘드네요. 저도 개인적으로는 Modifier 형태로 받아오는게 좋을 것 같습니다. 이게 지금은 바형태로 되어있고 필요한게 width, height밖에 없다고 하지만 이후에는 더 많은/적은 패러미터가 필요할 수 있으니까 변경에는 그다지 용이하지 않을 것 같네요.

2024-03-28 08:47 UTC, l2hyunwoo commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/part/PartRankingScreen.kt
> +        // TODO: Data fetch
Data fetch는 뷰모델에서!

2024-03-28 08:47 UTC, l2hyunwoo commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/part/PartRankingScreen.kt
> +            }
컴포즈에서는 트레일링 람다 쓰는 것보다 네임드 패러미터로 값 받아오는게 좋습니다. 저 람다가 어떤 역할을 하는지 지금 제가 봐도 모르겠네요.

2024-03-28 08:47 UTC, l2hyunwoo commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/part/PartRankingScreen.kt
> +    partRankList: List<PartRankModel>,
여기도 ImmutableList

2024-03-28 08:47 UTC, l2hyunwoo commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/part/PartRankingScreen.kt
> +                onClickBack = { resultNavigator.navigateBack() },
```suggestion
                onRefresh = partRankingViewModel::onRefresh,
                onClickBack = resultNavigator::navigateBack,
```

2024-03-28 08:47 UTC, l2hyunwoo commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/part/PartRankingScreen.kt
> +fun PartRankingBar(part: PartRankModel, width: Dp = 50.dp) {
여기도 Modifier로 받아오는게 좀 더 좋지 않을까...? 싶긴 합니다.

2024-03-28 08:47 UTC, l2hyunwoo commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/part/PartRankingScreen.kt
> +            color = Gray800
```suggestion
            color = SoptTheme.colors.onSurface80
```

2024-03-28 08:47 UTC, l2hyunwoo commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/part/PartRankingScreen.kt
> +            modifier = Modifier.weight(0.53f)
이런 수치로 주신 이유가 있을까요?

2024-03-28 08:47 UTC, l2hyunwoo commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/part/PartRankingScreen.kt
> +                fontWeight = FontWeight.Bold,
이 부분 정의가 안되어있던가요?

2024-03-28 10:18 UTC, chattymin commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/RankingBar.kt
> +            .size(width, height)
기존에 작성되어있던 코드를 따라서 작성하느라 이렇게 했었습니다!
제가 생각을 안하고 따라만 한것 같네요... 저도 modifier를 받는게 좋을 것 같으니 수정하겠습니다 :)

2024-03-28 10:20 UTC, chattymin commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/TopRankerItem.kt
> +        RankingBar(90.dp, height, ranker.rank) {
저도 그렇게 생각합니다! 실수로 지운 것 같아서 넣도록 하겠습니다

2024-03-28 10:20 UTC, chattymin commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/part/PartRankingScreen.kt
> +    refreshing: Boolean = false,
넘나 맞는 말입니다! 수정하겠습니다

2024-03-28 10:23 UTC, chattymin commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/part/PartRankingScreen.kt
> +    refreshing: Boolean = false,
저도 그렇게 생각하고 바꾸려 했는데 `rememberPullRefreshState`내부 값이 refreshing으로 설정되어있습니다
그렇기 때문에 의도적으로 맞춰두는 것이 더 나을 것 같습니다

2024-03-28 10:24 UTC, chattymin commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/part/PartRankingScreen.kt
> +        // TODO: Data fetch
viewModel에 있는 Data fetch하는 함수를 호출할 예정이다 라는 의미로 주석을 쓴 것 이었습니다...!!
주석을 쓸 때도 이런 부분까지도 생각하면서 작성하도록 하겠습니다!

2024-03-28 10:46 UTC, chattymin commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/part/PartRankingScreen.kt
> +                onClickBack = { resultNavigator.navigateBack() },
더블콜론은 intent에서 class 참조할때 습관적으로 사용했지 어떤건지 모르고 사용했네요!! 
덕분에 공부해보고 적용할 수 있는 기회가 되었습니다! 감사합니다 :)

2024-03-28 12:46 UTC, chattymin commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/list/MissionListScreen.kt
>      menuTexts: List<String>,
넵 적용 완료했습니다!

2024-03-28 13:00 UTC, chattymin commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/part/PartRankingScreen.kt
> +fun PartRankingBar(part: PartRankModel, width: Dp = 50.dp) {
이 코드는 제 실수로 남겨뒀습니다! 
기존에 있던 RankingBar를 확장성있게 바꾸고 Part에는 적용을 안시켰네요

좀더 꼼꼼히 코드 짜보겠습니다

2024-03-29 00:45 UTC, chattymin commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/part/PartRankingScreen.kt
> +            modifier = Modifier.weight(0.53f)
기존에 정의되어있던 수치 그대로 가지고 왔습니다

2024-03-29 01:33 UTC, chattymin commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/part/PartRankingScreen.kt
> +                fontWeight = FontWeight.Bold,
기존에 정의되어 있었는데 타입이 달라 새로 만들었습니다.
하지만 이 코멘트를 보고 생각해보니 기존 코드를 수정해서 재사용하는게 나을 것 같아 수정해봤습니다!

2024-03-29 01:41 UTC, l2hyunwoo approved these changes
확인해주시고 문제 있으시면 그냥 머지하세요

2024-03-29 01:41 UTC, l2hyunwoo commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/RankListItem.kt
> +fun RankListItem(
Any?

2024-03-29 02:21 UTC, giovannijunseokim commented
> 확인해주시고 문제 있으시면 그냥 머지하세요

없으시면 아닌가요 ..?

2024-03-29 02:28 UTC, l2hyunwoo commented
@giovannijunseokim 넘어가~

2024-03-29 02:29 UTC, chattymin commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/RankListItem.kt
> +fun RankListItem(
지금생각해보니 왜썼나 싶네요... 수정했습니다!

2024-03-29 05:39 UTC, merged