[Feature/kdh/#462-web-view] 인앱 브라우저 구현
sopt-makers/sopt-android pull request #654
Opened 2024-04-03 15:51 UTC by giovannijunseokim

## What is this issue?
- [x] 인앱 브라우저 구현 후 릴리즈 환경에서 테스트 완료

## Reference
- [x]

https://github.com/sopt-makers/sopt-android/assets/108331578/e768c973-ded1-4116-92d2-9fd51cadbcfb

close #462

2024-04-03 22:51 UTC, l2hyunwoo requested changes
다시 확인부탁드릴게요

2024-04-03 22:51 UTC, l2hyunwoo commented on core/webview/src/main/java/org/sopt/official/webview/view/WebViewActivity.kt
> +        Timber.d("LinkUrl: $mLinkUrl")
디버그 로그 삭제 부탁드립니다

2024-04-03 22:51 UTC, l2hyunwoo commented on core/webview/src/main/java/org/sopt/official/webview/view/WebViewActivity.kt
> +        val mLinkUrl = intent.getStringExtra(INTENT_URL)
변수에 m prefix 제거 부탁드립니다

2024-04-03 22:51 UTC, l2hyunwoo commented on core/webview/build.gradle.kts
이거 의존성 필요없는거 시스템이 자동추가한 것 같은데 확인 부탁드릴게여

2024-04-03 22:51 UTC, l2hyunwoo commented on core/webview/src/main/java/org/sopt/official/webview/view/WebViewActivity.kt
> +    private lateinit var binding: ActivityWebViewBinding
이거 viewBinding util 있지 않나요

2024-04-04 01:10 UTC, giovannijunseokim commented on core/webview/build.gradle.kts
Outdated라고 뜨면서 코드가 안 뜨는데 어느 부분일까요 !?

2024-04-04 01:24 UTC, l2hyunwoo commented on core/webview/build.gradle.kts
ㅋㅋㅋㅋ이거 리베이스 안하면서 이전 커밋에서 떴던 것 같습니다. 무시하셔도 될듯

2024-04-04 01:49 UTC, giovannijunseokim commented on core/webview/src/main/java/org/sopt/official/webview/view/WebViewActivity.kt
> +    private lateinit var binding: ActivityWebViewBinding
PokeActivity 참고해서 수정하겠습니다 !

2024-04-04 01:51 UTC, giovannijunseokim commented on core/webview/src/main/java/org/sopt/official/webview/view/WebViewActivity.kt
> +        Timber.d("LinkUrl: $mLinkUrl")
완료했습니다! 683a57f81c5d77aa20003226465858dc70affa87

2024-04-04 01:51 UTC, giovannijunseokim commented on core/webview/src/main/java/org/sopt/official/webview/view/WebViewActivity.kt
> +        val mLinkUrl = intent.getStringExtra(INTENT_URL)
완료했습니다! d5ed04679e78f34288a7eb577b683a05125b4e69

2024-04-04 04:43 UTC, l2hyunwoo approved these changes
👍🏻

2024-04-04 05:09 UTC, merged