feat/#651 stamp api + rank api
sopt-makers/sopt-android pull request #658
Opened 2024-04-04 11:45 UTC by chattymin

## What is this issue?
- [x] stamp api
- [x] rank api

## To Reviewer
- 서버에서 이미지 업로드 관련으로 문제가 하나 있어 아직 해결중입니다!
- 그래서 pre-signed url에 주석을 붙여두었습니다! 추후 서버에서 해결이 된다면 테스트 후 지우도록 하겠습니당
- 아래 코드의 경우 const를 넣고싶지만, const를 붙이니 spotlessApply에서 오류가 나오더라구요... 그래서 그냥 뒀습니다
```
private val startYear = 1950
private val endYear = 2100
```

2024-04-04 11:52 UTC, l2hyunwoo requested changes
일단 간략한 리뷰 달았는데...좀 크리티컬한 이슈가 담긴 코드도 있는 것 같네요. 확인 부탁드려요

2024-04-04 11:52 UTC, l2hyunwoo commented on data/soptamp/src/main/java/org/sopt/official/data/soptamp/remote/api/S3Service.kt
> +    suspend fun putS3Image(@Url preSignedURL: String, @Body image: RequestBody): Response<Unit>
```suggestion
    suspend fun putS3Image(@Url preSignedURL: String, @Body image: RequestBody)
```

Retrofit 2.10.0 이후로 Unit으로 리턴 가능해졌습니다.

2024-04-04 11:52 UTC, l2hyunwoo commented on domain/soptamp/src/main/kotlin/org/sopt/official/domain/soptamp/model/S3URL.kt
사실 도메인에 S3Url이 있다는게 좀 어불성설이긴 합니다..플랫폼에 종속되어있지 않아야 하는데 S3라는 플랫폼이 떡하니 있어서ㅋㅋㅋ이것도 한번 논의해봐야할 것 같아요.

2024-04-04 11:52 UTC, l2hyunwoo commented on feature/mypage/src/main/res/layout/activity_my_page.xml
안쓰는 부분 지워주세요.

2024-04-04 11:52 UTC, l2hyunwoo commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/detail/ContentUriRequestBody.kt
이거 core.common 같은 유틸성 패키지에 넣는게 좋지 않을까요?

2024-04-04 11:52 UTC, l2hyunwoo commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/detail/MissionDetail.kt
> +                                    Timber.e(uri.toString())
여기서 Timber.e를 사용하는게 적절할까요?

2024-04-04 11:52 UTC, l2hyunwoo commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/detail/MissionDetail.kt
> +                                    Timber.e(requestBody.toString())
여기서 Timber.e를 사용하는게 적절할까요? 222

2024-04-04 11:52 UTC, l2hyunwoo commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/detail/MissionDetailViewModel.kt
> +    // private val service: StampService,
안 쓰는 부분 삭제.

2024-04-04 11:52 UTC, l2hyunwoo commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/rank/RankingViewModel.kt
> +    )
enum class?

2024-04-04 11:58 UTC, chattymin commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/detail/MissionDetail.kt
> +                                    Timber.e(uri.toString())
제가 코드 확인용으로 썼는데 바보같이 안지웠네요...
정신이 없었던 것 같습니다!! 바로 지우겠습니담

2024-04-04 13:15 UTC, chattymin commented
> @chattymin 미완된 PR이라면 Draft + DO NOT MERGE 달아놓는 것이 좋아보여요 !!

오 이런기능도 있군요!! 감사합니다!!
구현은 다 했는데 서버가 불안정한거라 코드리뷰는 받고싶어서 draft는 안하고 DO NOT MERGE만 달아뒀습니다 ㅎㅎㅎ
다음번에 잘 활용하겠습니당

2024-04-12 08:48 UTC, l2hyunwoo requested changes
다시확인

2024-04-12 08:48 UTC, l2hyunwoo commented on gradle/libs.versions.toml
> -okhttp = { module = "com.squareup.okhttp3:okhttp" }
이거 이렇게 하지말고

2024-04-12 08:48 UTC, l2hyunwoo commented on core/common/build.gradle.kts
> +}
```suggestion
dependencies {
    implementation(platform(libs.okhttp.bom))
    implementation(libs.okhttp)
}
```

이렇게 해보셈. 그럼 okhttp 버전 지워도 됨

2024-04-13 06:12 UTC, chattymin commented on core/common/build.gradle.kts
> +}
적용 완료!!
platform이라는걸 처음봐서 공부하고 수정하느라 시간이 좀 걸렸습니다 ㅎㅎ

2024-04-13 10:15 UTC, l2hyunwoo reviewed
코멘트 확인해주세요

2024-04-13 10:15 UTC, l2hyunwoo commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/rank/RankingViewModel.kt
> +    enum class PART {
enum class 네이밍 컨벤션이 Upper snake case였나요?

2024-04-13 10:15 UTC, l2hyunwoo commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/rank/RankingViewModel.kt
> +            }
part <-> string 전환 로직은 어디에나 분포되어있을 수 있는데 이는 재사용성을 떨어뜨리는 주범이 될 수 있습니다. 코드 정리를 한번 해주시는 걸 추천드릴게요.

2024-04-13 10:15 UTC, l2hyunwoo commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/detail/component/DatePicker.kt
> +private val endYear = 2100
const 지운 이유가 있으신가요?

2024-04-13 14:37 UTC, chattymin commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/rank/RankingViewModel.kt
> +    enum class PART {
어머 Pascal Case였는데 왜 저렇게 했을까요...?
그저 바보였네요 수정하겠습니다

2024-04-13 14:41 UTC, chattymin commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/detail/component/DatePicker.kt
> +private val endYear = 2100
저도 처음에 const를 넣었는데 const가 있으니까 spotlessApply에서 오류가  나더라구요....?
왜인지 몰라서 해결을 못해서 const 빼버렸습니담...

2024-04-13 14:46 UTC, l2hyunwoo commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/mission/detail/component/DatePicker.kt
> +private val endYear = 2100
const는 네이밍 컨벤션이 어퍼 스네이크 케이스랍니다.

2024-04-13 15:07 UTC, chattymin commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/rank/RankingViewModel.kt
> +            }
제가 생각하기에 변환하는 코드가 따로 있으면 재사용성을 떨어뜨린다로 받아들였습니다.
그래서 enum class 내부에 변환 로직을 넣어 어디서 호출하더라도 똑같이 사용할 수 있도록 해봤습니다...

맞는지는 모르겠네요 ㅠㅠ

2024-04-13 15:11 UTC, l2hyunwoo reviewed
좋은 생각. 하지만 한번만 더 짱구를 굴려보세요

2024-04-13 15:11 UTC, l2hyunwoo commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/rank/RankingViewModel.kt
> +            }
얼토당토 않는 이름이 내려왔으면 null이 아니고 exception이 던져져야 상황상 적절하지 않을까요?

2024-04-13 15:11 UTC, l2hyunwoo commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/rank/RankingViewModel.kt
> +            private val partMap = entries.associateBy { it.part }
entries를 map으로 바꾸는 것 좋은 생각, 하지만 우리에게는 collection 함수가 있다. 이걸 한번 더 생각해봅시다.

2024-04-13 15:24 UTC, chattymin commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/rank/RankingViewModel.kt
> +            }
그게 맞는 방식인것 같습니다
제가 exception을 사용하는게 익숙치가 않아서 습관적으로 nulld을 던져버렸네요..!!

2024-04-13 16:10 UTC, chattymin commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/rank/RankingViewModel.kt
> +            private val partMap = entries.associateBy { it.part }
불필요한 변수를 날리고 find를 사용하는 방법을 생각해서 적용해봤습니다...!!

하지만 궁금한 부분이 하나 생겨 여쭤보려 합니다.
find 내부는 `firtstOrNull`이라는 함수 값을 리턴하게 되어있고, 해당 함수는 아래와 같이 구현되어있습니다
<img width="625" alt="image" src="https://github.com/sopt-makers/sopt-android/assets/52882799/41c4c58f-460e-46ff-a168-45ed31d9cacb">

이렇게 되면 for문을 진행하게 되어 map을 사용하는 것 보다 속도적 단점을 가지게 된다고 생각합니다.
어차피 enum class 내부에 값이 얼마 없어 속도적인 차이가 없다고 봐도 돼서 이렇게 쓰는 것인지, 아니면 다른 장점이 있는 것인지 궁금합니다.


또한, 기존 코드에서의 어떤 단점으로 인해 수정을 권유해주신 것인지 궁금합니다.
저는 map이란 불필요한 변수가 생기는 것과 그로인해 가독성이 떨어질 수 있다 라고 생각이 됩니다.

2024-04-13 16:14 UTC, l2hyunwoo commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/rank/RankingViewModel.kt
> +            private val partMap = entries.associateBy { it.part }
find라는 직관적인 함수를 활용해서 가독성을 높일 수 있고 정해진 양에서 find하는 로직은 O(n^2)로 짜나 심지어 저정도면 O(n!) 정도 알고리즘으로도 무리없이 빠르게 계산할 수 있습니다ㅋㅋㅋ 최대한 가독성 있게 가시죠

2024-04-13 16:16 UTC, l2hyunwoo approved these changes
수고하셨습니다.

2024-04-13 16:16 UTC, l2hyunwoo commented on feature/soptamp/src/main/java/org/sopt/official/stamp/feature/ranking/rank/RankingViewModel.kt
> +                return entries.find { it.part == part }?.name ?: throw throw IllegalArgumentException("Wrong Part Name")
```suggestion
return entries.find { it.part == part }?.name ?: throw throw IllegalArgumentException("Wrong Part Name $part")
```

에러를 발생시킨 원인도 같이 에러로그에 남기면 좋겠죠?

2024-04-13 16:26 UTC, merged