Attendance screen compose setting
sopt-makers/sopt-android pull request #676
Opened 2024-04-19 08:50 UTC by giovannijunseokim

## What is this issue?
- [x] 출석 화면 컴포즈 기초세팅

## Reference
- [x]

2024-04-19 09:11 UTC, chattymin approved these changes
고생하셨습니다 💪

2024-04-19 09:11 UTC, chattymin commented on app/src/main/java/org/sopt/official/feature/attendance/compose/AttendanceRoute.kt
> +    val action = AttendanceAction(viewModel)
이 action을 data class로 빼서 선언하신 이유가 있을까요??

2024-04-19 09:11 UTC, chattymin commented on app/src/main/java/org/sopt/official/feature/attendance/compose/AttendanceRoute.kt
> +                .padding(it)
저는 It보다는 `paddingValue`처럼 네이밍을 정해주는걸 선호합니다 ㅎㅎ

2024-04-19 09:11 UTC, chattymin commented on app/src/main/java/org/sopt/official/feature/attendance/compose/AttendanceRoute.kt
> +    val viewModel: NewAttendanceViewModel = viewModel()
hiltViewModel로 바꿔도 될 것 같아요!

2024-04-19 09:29 UTC, giovannijunseokim commented on app/src/main/java/org/sopt/official/feature/attendance/compose/AttendanceRoute.kt
> +    val action = AttendanceAction(viewModel)
빼서 선언한 이유는 Action에 대한 정의를 다른 클래스로 빼고 싶어서입니다!
내부에 로직 없이 프로퍼티들(람다)만 있다보니 data 클래스로 선언했는데 그냥 class로 변경해도 될 것 같네요.

2024-04-19 09:31 UTC, giovannijunseokim commented on app/src/main/java/org/sopt/official/feature/attendance/compose/AttendanceRoute.kt
> +                .padding(it)
이 부분 놓쳤네요. 감사합니다!
626a584c543a7b4d0acb8d45e9baeb2ce6b8d8d5

2024-04-19 09:49 UTC, giovannijunseokim commented on app/src/main/java/org/sopt/official/feature/attendance/compose/AttendanceRoute.kt
> +    val viewModel: NewAttendanceViewModel = viewModel()
음 둘 중 무엇이 더 좋을지 고민중인데, hiltViewModel을 추천해주신 이유가 있을까요 !?

2024-04-20 03:40 UTC, l2hyunwoo requested changes
다시 한번 확인 부탁드립니다.

2024-04-20 03:40 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/attendance/NewAttendanceActivity.kt
> +            SoptTheme(darkTheme = false) {
darkTheme false는 굳이 명시안해줘도 될 것 같습니다.

2024-04-20 03:40 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/attendance/NewAttendanceViewModel.kt
> +    private val _uiState: MutableStateFlow<AttendanceUiState> = MutableStateFlow(AttendanceUiState.Loading)
Loading보단 Idle이 초기상태 이름에 더 적절하지 않나 생각합니다.

2024-04-20 03:40 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/attendance/NewAttendanceViewModel.kt
> +    private var fakeTitle: String = ""
이 프로퍼티의 존재의미는 무엇인가요?

2024-04-20 03:40 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/attendance/NewAttendanceViewModel.kt
> +    }
이 친구는? 만약에 아무 행동도 정의안할 함수면

```suggestion
    fun onClickFake() = Unit
```

혹은

```suggestion
    fun onClickFake() {
        // TODO by Junseo 구현해아할 함수
    }
```
정도로 적을 수 있을 것 같습니다.

2024-04-20 03:40 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/attendance/compose/AttendanceRoute.kt
> +    }) { innerPaddingValues ->
```suggestion
    Scaffold(
        topBar = {
            TopAppBar(title = { Text(text = "출석") })
        }
    ) { innerPaddingValues ->
```

2024-04-20 03:40 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/attendance/compose/AttendanceRoute.kt
> +    val viewModel: NewAttendanceViewModel = viewModel()
[REFERENCE](https://developer.android.com/develop/ui/compose/libraries#hilt)

2024-04-20 03:40 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/attendance/compose/AttendanceRoute.kt
> +}
이거 프리뷰 안보일텐데 체크하고 넘어가신건가요?

2024-04-20 03:40 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/attendance/model/AttendanceAction.kt
> +    val onFakeClick: () -> Unit = viewModel::updateUiState
음...이 액션 클래스의 존재의의는 잘 모르겠네요. 액션이라는 것은 뷰모델에 전달하는 메시지 같은 느낌입니다. 뷰모델에게 액션을 전달하는 것과 액션이 뷰모델을 호출하는 것은 결과는 비슷할 수 있으나 그 과정은 아예 다른 것으로 볼 수 있어요,

2024-04-20 03:40 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/attendance/compose/AttendanceScreen.kt
> +
구현 안된 함수는 TODO 붙이기

2024-04-20 03:40 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/attendance/compose/AttendanceScreen.kt
> +
참고로 AttendanceAction은 뷰모델을 참조하고 있는데, ViewModel은 Stable하지 않은 클래스여서 이 Screen함수는 Skippable하지 않습니다.

2024-04-21 14:23 UTC, giovannijunseokim commented on app/src/main/java/org/sopt/official/feature/attendance/NewAttendanceActivity.kt
> +            SoptTheme(darkTheme = false) {
아 기본값이 false였군요 감사합니다 !

2024-04-21 14:26 UTC, giovannijunseokim commented on app/src/main/java/org/sopt/official/feature/attendance/NewAttendanceViewModel.kt
> +    private val _uiState: MutableStateFlow<AttendanceUiState> = MutableStateFlow(AttendanceUiState.Loading)
요 부분에 대해서 고민해봤는데, 기존 Idle을 삭제한 이유는 뷰모델 init 블록에서부터 data를 가져오기 때문에 맨 처음 상태를 Loading으로 두어도 될 것 같다고 판단했습니다. 초기부터 Loading이라고 생각했는데, Idle이 필요한 이유가 있을까요??

2024-04-21 14:28 UTC, giovannijunseokim commented on app/src/main/java/org/sopt/official/feature/attendance/NewAttendanceViewModel.kt
> +    private var fakeTitle: String = ""
여기에 뷰에 필요한 값들을 적는다는 것을 표현하기 위해 필요없는 값을 하나 넣어두었습니다.
추후 그럴 경우엔 오히려 주석을 추가해두는 것이 좋을 것 같네요! 변수는 삭제해두도록 하겠습니다.

2024-04-21 14:30 UTC, giovannijunseokim commented on app/src/main/java/org/sopt/official/feature/attendance/NewAttendanceViewModel.kt
> +    }
요 부분은 임의로 만들어둔거라 삭제하도록 하겠습니다 !

2024-04-21 14:34 UTC, giovannijunseokim commented on app/src/main/java/org/sopt/official/feature/attendance/compose/AttendanceRoute.kt
> +    }) { innerPaddingValues ->
요 부분은 reformat code 하니 위처럼 바뀌는데, 제안해주신대로 바꾸는 것이 좋을까요??

2024-04-21 14:34 UTC, giovannijunseokim commented on app/src/main/java/org/sopt/official/feature/attendance/compose/AttendanceRoute.kt
> +}
제 컴퓨터 문제인줄 알고 그냥 넘겼는데 아니었군요 😅
프리뷰가 안 보이는 이유는 뷰모델 때문일까요??

2024-04-21 15:08 UTC, giovannijunseokim commented on app/src/main/java/org/sopt/official/feature/attendance/model/AttendanceAction.kt
> +    val onFakeClick: () -> Unit = viewModel::updateUiState
스크린, 화면에 보여질 값들을 state에 넣고 동작들은 action에 넣어 전달했는데, 동작들 또한 State에 넣는 것이 좋을까요?

2024-04-21 15:12 UTC, giovannijunseokim commented on app/src/main/java/org/sopt/official/feature/attendance/compose/AttendanceRoute.kt
> +    val viewModel: NewAttendanceViewModel = viewModel()
hiltViewModel과 viewModel의 차이는 Scope의 차이로 알고 있는데, 출석 화면에선 네비게이션이 일어나지 않아 고민됩니다 ㅠ 제가 아는 것 외의 차이도 있을까요 ??

2024-04-21 15:26 UTC, giovannijunseokim commented on app/src/main/java/org/sopt/official/feature/attendance/compose/AttendanceScreen.kt
> +
TODO 추가하였습니다! c16a8721be4edcc1278704c3b59a5a31ff23f823

2024-04-21 15:31 UTC, giovannijunseokim commented on app/src/main/java/org/sopt/official/feature/attendance/compose/AttendanceScreen.kt
> +
AttendanceAction을 넘기는 순간 Screen 내부가 모두 recomposition이 일어나 성능 이슈가 발생하겠네요 ㅠ 레퍼런스를 좀 더 찾아보겠습니다.

2024-04-21 15:48 UTC, l2hyunwoo approved these changes
일단 액션쪽 수정은 세팅 PR 머지 이후에 진행해도 괜찮을 것 같습니다(시간이 좀 오래걸릴 것 같은 느낌). 다른 리뷰들도 같이 확인해주시고 문제 없으면 머지해주세요.

2024-04-21 15:48 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/attendance/NewAttendanceViewModel.kt
> +    private val _uiState: MutableStateFlow<AttendanceUiState> = MutableStateFlow(AttendanceUiState.Loading)
화면에 제일 초기 상태는 Idle이어서 의미론상으로 접근을 해봤는데 복잡한 화면이 아니라면 Loading으로 대체할 수 있을 것 같네요. 구현하다가 로직에 Idle 추가가 필요하다면 그때 해도 괜찮을 것 같습니다.

2024-04-21 15:48 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/attendance/NewAttendanceViewModel.kt
> +    private var fakeTitle: String = ""
일단 오케이, 나중에 UI Data 포맷 반영하면서 수정하셔도 될 것 같습니다.

2024-04-21 15:48 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/attendance/compose/AttendanceRoute.kt
> +    val viewModel: NewAttendanceViewModel = viewModel()
일단 이걸로 가셔도 됩니다.

2024-04-21 15:48 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/attendance/compose/AttendanceRoute.kt
> +    }) { innerPaddingValues ->
일단 가독성도 그렇고, topBar 이외에 더 추가될 수 있는 컴포넌트들이 있어서 이렇게 바꾸는 걸 권장드립니다.

2024-04-21 15:48 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/attendance/model/AttendanceAction.kt
> +    val onFakeClick: () -> Unit = viewModel::updateUiState
액션(상태 변경/어떤 동작에 대한 요청)과 상태는 별개입니다(우체국하고 편지와의 관계정도로 보시면 될 것 같습니다). 동작을 State안에 넣는다는 것은 Action이 State의 집합 내에 속한다고 생각을 하시는 것 같아서요. 

UI 내에서 상태를 어떤 구조로 처리할 지에 대해 좀 더 명확한 가이드라인이 세워지면 좋을 것 같습니다. 이건 동민이랑 같이 논의해봐도 좋을 것 같고 필요하면 저도 불러주세요.

2024-04-21 16:12 UTC, giovannijunseokim commented on app/src/main/java/org/sopt/official/feature/attendance/compose/AttendanceScreen.kt
> +
이런식으로 수정해보았습니다. Action 클래스 내부 ViewModel 참조를 없앴고, composable function의 파라미터로 뷰모델을 받은 후 뷰모델 내부 함수의 참조값만을 전달했습니다! 
b759e753224440fbd9a3fb7851e9064519619836

2024-04-21 16:13 UTC, giovannijunseokim commented on app/src/main/java/org/sopt/official/feature/attendance/compose/AttendanceRoute.kt
> +    }) { innerPaddingValues ->
e67066b06657f921ddf99a6ef68a5ae869be4561
수정하였습니다!

2024-04-21 16:15 UTC, giovannijunseokim commented
밀도있는 코드리뷰 감사드립니다🙇‍♂️🙇‍♂️ @l2hyunwoo

2024-04-22 05:00 UTC, merged