#709 Feat: Soptamp Darkmode
sopt-makers/sopt-android pull request #713
Opened 2024-05-26 16:59 UTC by 0se0

## What is this issue?
- [x]

## Reference
- [x]

2024-05-26 23:21 UTC, l2hyunwoo requested changes
수고하셨습니다. 리뷰 확인해주세요.

2024-05-26 23:21 UTC, l2hyunwoo commented on feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/style/Theme.kt
> +fun SoptTheme( darkTheme: Boolean = isSystemInDarkTheme(), content: @Composable () -> Unit) {
```suggestion
fun SoptTheme(darkTheme: Boolean = isSystemInDarkTheme(), content: @Composable () -> Unit) {
```

터미널에서 `./gradlew spotlessApply` 한번만 돌려주세요

2024-05-26 23:21 UTC, l2hyunwoo commented on feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/style/Theme.kt
> +    AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_FOLLOW_SYSTEM)
해당 설정은 이미 App 클래스에서 MODE_NIGHT_NO로 가져가고 있기 때문에, 다크모드를 켜야할 경우엔 App 클래스에서 그 부분 코드만 지우면 충분히 전환가능합니다 :) 이 코드는 넣을 필요가 없을 것 같아요.

2024-05-27 17:04 UTC, 0se0 commented on feature/soptamp/src/main/java/org/sopt/official/stamp/designsystem/style/Theme.kt
> +    AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_FOLLOW_SYSTEM)
오! 그렇군요 차마 확인하지 못했습니다!! 적용하였습니다. 감사합니다~!

2024-05-27 22:58 UTC, l2hyunwoo approved these changes
LGTM 👍

2024-05-27 23:01 UTC, merged