[feature/#712] poke onboarding with anonymous
sopt-makers/sopt-android pull request #721
Opened 2024-05-30 17:04 UTC by chattymin

## What is this issue?
closed #712 
- [x] onboardingBottomSheet 수정
- [x] ViewPager2를 활용한 Onboarding Friend 추천 화면 구현

## Video

https://github.com/sopt-makers/sopt-android/assets/52882799/ad32f0bc-a815-4b0e-9768-45ea08ed69a9

## To Reviewer
- 온보딩 첫 진입시 안내 bottomSheet는 앱 다운 후 첫 입장시에만 뜨도록 설정해두었습니다
- 온보딩에 첫 진입시 친구 추천의 경우 최초는 "ALL"을 활용하여 서버에서 주는 모든 값을 받도록 하였습니다. 동적으로 조정하여 현재는 3개지만, 그 이상 혹은 그 이하가 되더라도 자동으로 반영되도록 하였습니다.
- 각 fragment에서 pull to refresh 할 경우 해당 화면만 새로고침 되어야 한다는 명세를 지키기 위해 viewModel을 만들어 각각 넣어줬습니다.
- 온보딩 화면에서 viewPager2 내부 Fragment에서 세로 스크롤 되는 것은 디자인 승인 받았습니다!

2024-05-30 20:53 UTC, l2hyunwoo requested changes
일단 좀 해결할 수 있는/짚고 넘어갈 수 있는 이슈들부터 같이 살펴보도록 하죠

2024-05-30 20:53 UTC, l2hyunwoo commented on core/common/src/main/java/org/sopt/official/common/util/Bundle.kt
`BundleCompat.getSerializable` 사용하면 됩니다. 이 코드는 지워주세요

2024-05-30 20:53 UTC, l2hyunwoo commented on data/poke/src/main/java/org/sopt/official/data/poke/source/local/PokeLocalDataSource.kt
>      }
이거 사용자 입장에서는 마이그레이션 코드 없이 그냥 이걸로 가는건데 괜찮으려나? 혹시 Shared Preference 이거 변경전하고 변경후에 isNewInPokeOnboarding 저장된거 지워져있는지 확인해 봤나요?

2024-05-30 20:53 UTC, l2hyunwoo commented on data/poke/src/main/java/org/sopt/official/data/poke/source/remote/PokeRemoteDataSource.kt
> +        val call = service.getOnboardingPokeUserList(randomType, size)
변수 이름이 call로 되어있는데 그냥 response로 해도 될 것 같아요

2024-05-30 20:53 UTC, l2hyunwoo commented on data/poke/src/main/java/org/sopt/official/data/poke/source/remote/PokeRemoteDataSource.kt
>          val call =
여기도

2024-05-30 20:53 UTC, l2hyunwoo commented on feature/poke/build.gradle.kts
> +    implementation("com.tbuonomo:dotsindicator:5.0")
버전 카탈로그에 있을 것 같습니다. 없으면 등록해주세요

2024-05-30 20:53 UTC, l2hyunwoo commented on feature/poke/build.gradle.kts
>      implementation(project(":core:analytics"))
```suggestion
    implementation(projects.core.analytics)
```

2024-05-30 20:53 UTC, l2hyunwoo commented on feature/poke/src/main/java/org/sopt/official/feature/poke/friend/detail/FriendListDetailBottomSheetFragment.kt
> +            override fun onScrolled(recyclerView: RecyclerView, dx: Int, dy: Int) {
시간되면 여기 Paging3로 마이그레이션 ㄱㄱ

2024-05-30 20:53 UTC, l2hyunwoo commented on feature/poke/src/main/java/org/sopt/official/feature/poke/onboarding/OnboardingPokeUserFragment.kt
새로 화면 만드는거였으면 그냥 Compose로 짜도 됐을듯?

2024-05-30 20:53 UTC, l2hyunwoo commented on feature/poke/src/main/java/org/sopt/official/feature/poke/onboarding/OnboardingPokeUserFragment.kt
> +    private val args by lazy { arguments?.getVersioningSerializable<OnboardingActivity.StartArgs>(ARG_ARGS) }
이것도 common 모듈에 있는것처럼 위임 프로퍼티 형식으로 가져오는거 고려해보면 좋을듯

2024-05-30 20:53 UTC, l2hyunwoo commented on feature/poke/src/main/java/org/sopt/official/feature/poke/onboarding/model/PokeUsers.kt
> +) : Serializable {
```suggestion
data class PokeOnboardingUiState(
    val randomType: String,
    val randomTitle: String,
    val userInfoList: List<PokeUsers>,
) : Serializable {
```

정도는 어떨까요?

2024-05-31 01:50 UTC, chattymin commented on feature/poke/build.gradle.kts
> +    implementation("com.tbuonomo:dotsindicator:5.0")
아 일단 돌아가는지 확인하고 수정하려고 했는데 깜빡했네요 ㅠㅠ
없어서 등록했고, 버전 카탈로그로 수정했습니다!!

2024-05-31 01:54 UTC, chattymin commented on feature/poke/src/main/java/org/sopt/official/feature/poke/onboarding/model/PokeUsers.kt
> +) : Serializable {
화면에 나타내는 정보이자 유지해야하는 정보이기 때문에 State로 해두는게 맞는 말 같습니다! 
수정했습니다 :)

2024-05-31 02:30 UTC, chattymin commented on feature/poke/src/main/java/org/sopt/official/feature/poke/onboarding/OnboardingPokeUserFragment.kt
Acitity 내부의 ViewPager에 들어가는 Fragment라 xml로 하는게 좋을 것 같습니다!!
기존 컴포넌트들을 재활용할 수 있고, 이번 마감기한이 촉박해서 xml을 유지하는게 좋다고 생각했습니다!

그리고 제가 xml이 compose보다 미숙하다 생각해 이 기회에 실력을 다져볼 수 있어서 xml로 했습니다 :)

2024-05-31 05:46 UTC, chattymin commented on data/poke/src/main/java/org/sopt/official/data/poke/source/remote/PokeRemoteDataSource.kt
> +        val call = service.getOnboardingPokeUserList(randomType, size)
사실 기존 코드가 call로 되어있어 그대로 유지했는데 초기에 call로 해둔 이유와, 이번에는 response로 변경하는 이유를 알 수 있을까요???

저는 service의 함수들이 전부 Response<T>를 return하기때문에 response가 맞다고 생각합니다

2024-05-31 06:03 UTC, chattymin commented on feature/poke/src/main/java/org/sopt/official/feature/poke/friend/detail/FriendListDetailBottomSheetFragment.kt
> +            override fun onScrolled(recyclerView: RecyclerView, dx: Int, dy: Int) {
이 부분은 이슈로 남겨두고 스프린트 구현 내용 완료하면 진행해도 괜찮을까요??
이번 스프린트 마감이 빠듯해 구현부터 완성해야 할 것 같습니다... ㅠㅠ

괜찮다면 이번 스프린트 마감 후 작업하도록 하겠습니다!

2024-05-31 07:05 UTC, chattymin commented on feature/poke/src/main/java/org/sopt/official/feature/poke/onboarding/OnboardingPokeUserFragment.kt
> +    private val args by lazy { arguments?.getVersioningSerializable<OnboardingActivity.StartArgs>(ARG_ARGS) }
<img width="620" alt="image" src="https://github.com/sopt-makers/sopt-android/assets/52882799/a6fad918-a09c-494e-a62a-4528daed8aea">

기존에 작성된 것 처럼 by lazy를 사용해도 위임 프로퍼티로 작동되는 것으로 알고있습니다. 혹시 extension을 만들어서 위임 프로퍼티를 하는 것과 어떤 차이가 있나요??

extension에서는 readOny로 되어있는데 by lazy로 선언해도 val이기 때문에 수정이 불가능해서 readOnly와 같은 역할을 할 수 있다고 생각합니다.
그 외에는 defaultValue가 있다는것 밖에는 알아차리지 못하겠네요...

2024-05-31 08:06 UTC, l2hyunwoo commented on feature/poke/src/main/java/org/sopt/official/feature/poke/friend/detail/FriendListDetailBottomSheetFragment.kt
> +            override fun onScrolled(recyclerView: RecyclerView, dx: Int, dy: Int) {
구현먼저하시고 “시간 남으시면” paging3 migrationㅋㅋ

2024-06-01 10:30 UTC, l2hyunwoo commented on data/poke/src/main/java/org/sopt/official/data/poke/source/local/PokeLocalDataSource.kt
>      }
👍🏻 네 조사 감사합니다. 이건 아마 특정 파일 주소나 파일 이름 난독화 걸어서 그런 것 같은데 저도 확실치는 않네요....

2024-06-01 10:30 UTC, l2hyunwoo commented on data/poke/src/main/java/org/sopt/official/data/poke/source/remote/PokeRemoteDataSource.kt
> +        val call = service.getOnboardingPokeUserList(randomType, size)
예전에 받아오는 함수가 전부 Call 타입으로 받아오지 않았을까요...? 아니면 그냥 response로 변경하는게 좋다고 생각합니다.

2024-06-01 10:32 UTC, l2hyunwoo commented on feature/poke/src/main/java/org/sopt/official/feature/poke/onboarding/OnboardingPokeUserFragment.kt
> +    private val args by lazy { arguments?.getVersioningSerializable<OnboardingActivity.StartArgs>(ARG_ARGS) }
아 by serializableExtra()나 by serializableArgument()로 하면 조금더 가독성이 좋아져서 그런거였어요. 가져올때도 코드 많이 안적고 저것만 적으면 가져와지니까 편하기도 하구요.

2024-06-01 10:33 UTC, l2hyunwoo requested changes

2024-06-01 10:33 UTC, l2hyunwoo commented on feature/poke/src/main/java/org/sopt/official/feature/poke/onboarding/OnboardingPokeUserFragment.kt
> +    private val args by serializableExtraFragment(OnboardingActivity.StartArgs(0, ""))
프라그먼트에서 가져올 때는 [argument 형식](https://github.com/TeamPophory/pophory-android/blob/develop/core/common/src/main/java/com/teampophory/pophory/common/intent/ArgsExt.kt)으로 받아오는게 맞을거에요

2024-06-02 11:16 UTC, chattymin commented on feature/poke/src/main/java/org/sopt/official/feature/poke/onboarding/OnboardingPokeUserFragment.kt
> +    private val args by serializableExtraFragment(OnboardingActivity.StartArgs(0, ""))
```
inline fun <reified S: Serializable>serializableArgs() = ReadOnlyProperty<Fragment, S?> { thisRef, property ->
    thisRef.requireArguments().getSerializable(property.name) as S?
}
```
이러한 방식으로 구현하였습니다! 예시로 주신 다른 Args 함수들도 같이 추가하였습니다.
하지만 궁금한 부분이 있어 질문 남깁니다.


1. `getSerializable`은 deprecated되었다고 표시됩니다. 그렇다면 이전에 작성했던 Bundle의 확장함수를 다시 추가해서 적용하는건 어떨까요?
```
inline fun <reified T : Serializable> Bundle.getVersioningSerializable(key: String): T? {
    return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
        getSerializable(key, T::class.java)
    } else {
        @Suppress("DEPRECATION")
        getSerializable(key) as? T
    }
}
```
2. `as`를 통한 타입캐스팅을 안정성을 이유로 저는 선호하지 않습니다. 하지만 이 상황의 경우 확실하기 때문에 as를 사용했는데 괜찮을까요? 그게 아니라면 if문을 이용해 `is S?`로 검사 후 null 혹은 실제 값을 리턴하려 합니다.

2024-06-02 22:55 UTC, l2hyunwoo commented on feature/poke/src/main/java/org/sopt/official/feature/poke/onboarding/OnboardingPokeUserFragment.kt
> +    private val args by serializableExtraFragment(OnboardingActivity.StartArgs(0, ""))
1. 그땐 제가 BundleCompat을 몰랐나이다
2. BundleCompat 사용하시면 타입 안정성 지켜질거에요

2024-06-02 23:00 UTC, l2hyunwoo approved these changes
리뷰 확인해보시고 넘어가도 되는 것이다 싶으면 반영안하셔도 됩니다. LGTM 👍🏻

2024-06-03 05:05 UTC, chattymin commented on feature/poke/src/main/java/org/sopt/official/feature/poke/message/MessageListBottomSheetFragment.kt
> +            activity?.showPokeToast(getString(R.string.toast_poke_anonymous_off))
showPokeToast가 Activity, Fragment의 확장함수로 선언되어있어 애초에 `activity? / requireActivity`를 안쓰고 그냥 써도 됐었네요... 
수정했습니다 :)

2024-06-03 05:14 UTC, chattymin commented on feature/poke/src/main/java/org/sopt/official/feature/poke/onboarding/OnboardingPokeUserFragment.kt
> +    private val args by serializableExtraFragment(OnboardingActivity.StartArgs(0, ""))
징차 최곱니다...
위에 코리에서 이걸 배웠으면서 기존 코드 형식을 유지해야한다는 생각에 적용을 안했네요..

parcelableArgs / serializableArgs 둘다 바로 반영해버렸습니다!

2024-06-03 05:44 UTC, chattymin commented on feature/poke/src/main/java/org/sopt/official/feature/poke/onboarding/OnboardingActivity.kt
> +        }
이 부분의 경우 acitivty가 생성될 때 한번만 실행되는 로직입니다! 
이후에는 각각 fragment에서 update하기 때문에 데이터가 추가적으로 업데이트 되지 않아 걱정하시는 상황은 발생하지 않습니다. 

현재는 총 3가지 경우만 받아오지만, 추후 그 이상 늘어날 것을 대비하여 `ALL`타입으로 모든 종류의 데이터를 받아와 동적으로 viewPager에 연결해줌과 동시에 dotsIndicator과도 연결해주고 있습니다.

2024-06-03 05:45 UTC, chattymin commented on feature/poke/src/main/java/org/sopt/official/feature/poke/onboarding/OnboardingPokeUserFragment.kt
> +        get() = requireNotNull(_binding) { "ERROR" }
이 프로젝트에는 없습니다!
없는 이유가 있는줄 알고 안만들고 사용하고있었는데 스프린트 개발 끝나고 여유생기면 만들고 적용해보겠습니다 :)

2024-06-03 05:48 UTC, l2hyunwoo commented on feature/poke/src/main/java/org/sopt/official/feature/poke/onboarding/OnboardingActivity.kt
> +        }
👍🏻

2024-06-03 05:50 UTC, merged