[feature/#725] poke ananymous
sopt-makers/sopt-android pull request #732
Opened 2024-06-08 14:39 UTC by chattymin

## What is this issue?
- [x] 익명 유저 정체 공개
- [x] 익명 관련 class 변경
- [x] 1차 qa사항 반영 

## Video
쉬운 연출을 위해 페이지 이동시 바로 뜨도록 했습니다. 실제와 다른부분이 있습니다.
단짝친구 | 천생연분
:--: | :--:
<video src="https://github.com/sopt-makers/sopt-android/assets/52882799/6e684f62-827d-4083-b7d5-b2467213af9f" width="300" /> | <video src="https://github.com/sopt-makers/sopt-android/assets/52882799/d941e441-d7c8-478e-b863-2640f88e1db8" width="300" />

## To Reviewer
- 개발기간이 빠듯해 후다닥 하다가 또 통짜 PR 올려버렸습니다... 죄송합니답...
- 코드도 좀 더 다듬을 수 있을 것 같은데 아쉽네요

2024-06-08 15:10 UTC, l2hyunwoo requested changes
일단 리뷰 한번 보시고....이후에 수정된거 또 리뷰 남길게요

2024-06-08 15:10 UTC, l2hyunwoo commented on feature/poke/src/main/java/org/sopt/official/feature/poke/friend/detail/FriendListDetailBottomSheetFragment.kt
> +                    override fun onAnimationEnd(animation: Animator) {
이거 확장함수 만들어서 `View.doOnAnimationEnd { }` 같은걸로 사용하면 좋을듯

2024-06-08 15:10 UTC, l2hyunwoo commented on feature/poke/src/main/java/org/sopt/official/feature/poke/friend/detail/FriendListDetailBottomSheetFragment.kt
> +                            }, 2000)
`lifecycleScope.launch`...?

2024-06-08 15:10 UTC, l2hyunwoo commented on feature/poke/src/main/java/org/sopt/official/feature/poke/friend/detail/FriendListDetailBottomSheetFragment.kt
> +                            }, 2000)
아 또 막 중복해서 하면 취소하고 해야돼서 그래가지고 안한건가...근데 그렇게 해도 중복해서 실행된다면(따닥) 취소해야하는건 매한가지일텐데

2024-06-08 15:10 UTC, l2hyunwoo commented on feature/poke/src/main/java/org/sopt/official/feature/poke/friend/summary/FriendListSummaryActivity.kt
> +                        if ((it.data.pokeNum == 5 || it.data.pokeNum == 6) && it.data.isAnonymous) { // 익명 베스트 프랜드 + 힌트
Magic Number 지양해주세요, 그리고 이 조건이 무슨 조건인지는 주석만으로는 파악하기 힘들 수 있으니 조건 자체를 property나 함수로 빼는걸 권장합니다.

2024-06-08 15:10 UTC, l2hyunwoo commented on feature/poke/src/main/java/org/sopt/official/feature/poke/friend/summary/FriendListSummaryActivity.kt
> +                        } else if ((it.data.pokeNum == 11 || it.data.pokeNum == 12) && it.data.isAnonymous) { // 익명 소울메이트 + 정체 공개
이것도 마찬가지

2024-06-08 15:10 UTC, l2hyunwoo commented on feature/poke/src/main/java/org/sopt/official/feature/poke/main/PokeMainActivity.kt
> +                is UiState.Loading -> "Loading"
이거 워닝뜨는데 수정 부탁드리겠습니다.

2024-06-08 15:10 UTC, l2hyunwoo commented on feature/poke/src/main/java/org/sopt/official/feature/poke/main/PokeMainActivity.kt
> +                                if ((it.data.pokeNum == 5 || it.data.pokeNum == 6) && it.data.isAnonymous) { // 익명 베스트 프랜드 + 힌트
이후에 나오는 조건문도 다 똑같이 프로퍼티 혹은 함수 추출해주시면 감사하겠습니다.

2024-06-09 15:17 UTC, chattymin commented on feature/poke/src/main/java/org/sopt/official/feature/poke/friend/detail/FriendListDetailBottomSheetFragment.kt
> +                    override fun onAnimationEnd(animation: Animator) {
오 이건 생각 못해봤는데 좋을 것 같네요!! 반영하겠습니다 :)

2024-06-09 16:29 UTC, chattymin commented on feature/poke/src/main/java/org/sopt/official/feature/poke/main/PokeMainActivity.kt
> +                is UiState.Loading -> "Loading"
이 부분은 기존에 그렇게되어있어 똑같이 했었던 거라 기존 코드도 전부 수정했습니다!
Loading일때는 아무 액션도 하지 않는 것으로 기존 의도를 파악해 아래와 같이 수정했습니다
`is UiState.Loading -> {}`

2024-06-09 16:43 UTC, chattymin commented on feature/poke/src/main/java/org/sopt/official/feature/poke/friend/detail/FriendListDetailBottomSheetFragment.kt
> +                            }, 2000)
음... 둘의 차이점을 찾아보니 lifecycleScope를 쓰는게 더 좋을 것 같습니다! 수정하도록 하겠습니다 :)

2024-06-09 17:04 UTC, chattymin commented on feature/poke/src/main/java/org/sopt/official/feature/poke/friend/summary/FriendListSummaryActivity.kt
> +                        if ((it.data.pokeNum == 5 || it.data.pokeNum == 6) && it.data.isAnonymous) { // 익명 베스트 프랜드 + 힌트
넵 알겠습니다. 함수로 빼서 진행하도록 하겠습니다!

2024-06-09 22:37 UTC, l2hyunwoo approved these changes
저 부분만 수정하고 바로 머지하시면 될 것 같습니다.

2024-06-09 22:37 UTC, l2hyunwoo commented on core/common/src/main/java/org/sopt/official/common/util/View.kt
> +}
인라인화해서 성능 올려주시면 더 좋을듯 하네요

2024-06-10 01:00 UTC, chattymin commented on core/common/src/main/java/org/sopt/official/common/util/View.kt
> +}
저 코드는 지운 코든데 깃허브에 기록이 남아있어 버렸군요... 

LottieAnimationView로 바꾼 코드에서 수정했습니다 :)
```
inline fun LottieAnimationView.addOnAnimationEndListener(crossinline action: () -> Unit) {
    this.addAnimatorListener(object : Animator.AnimatorListener {
        override fun onAnimationStart(animation: Animator) {}

        override fun onAnimationEnd(animation: Animator) {
            action()
        }

        override fun onAnimationCancel(animation: Animator) {}

        override fun onAnimationRepeat(animation: Animator) {}
    })
}
```

2024-06-10 01:03 UTC, merged