Attendance history card 구현
sopt-makers/sopt-android pull request #733
Opened 2024-06-10 06:40 UTC by giovannijunseokim

## What is this issue?
- [x] Attendance history card 구현
<img width="372" alt="스크린샷 2024-06-10 오후 3 39 26" src="https://github.com/sopt-makers/sopt-android/assets/108331578/42ae0379-3336-4a77-b360-840f5cebbf52">

## Reference
- [x]

2024-06-10 06:41 UTC, giovannijunseokim commented on app/src/main/java/org/sopt/official/feature/attendance/compose/component/AttendanceCountCard.kt
> +fun Int.toFormattedNumber(): String = "%02d회".format(this)
이친구 적당한데로 옮겨놓고 싶은데 어디가 괜찮을까요 ??

2024-06-10 06:44 UTC, l2hyunwoo requested changes
리뷰 참고해보세요

2024-06-10 06:44 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/attendance/compose/component/AttendanceHistoryCard.kt
> +    attendanceHistoryList: List<AttendanceHistory>,
리컴포지션 안정성에 취약한 구조여서...[Immutable Collections](https://github.com/Kotlin/kotlinx.collections.immutable) 사용 고려해보시는게 좋습니다.

(물론 지금 스트롱 스키핑 적용해서 괜찮긴 할겁니다)

2024-06-10 06:44 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/attendance/compose/component/AttendanceHistoryListCard.kt
> +    attendanceHistoryList: List<AttendanceHistory>,
이것도

2024-06-10 06:44 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/attendance/compose/component/AttendanceHistoryUserInfoCard.kt
> +        }
이거 그냥 horizontalArrangement로 SpaceBetween 적용하면 될지도?

2024-06-10 06:50 UTC, giovannijunseokim commented on app/src/main/java/org/sopt/official/feature/attendance/compose/component/AttendanceHistoryUserInfoCard.kt
> +        }
<img width="273" alt="스크린샷 2024-06-10 오후 3 48 42" src="https://github.com/sopt-makers/sopt-android/assets/108331578/83b28916-b3c7-48c1-a1eb-5377ec89f78a">
정보 아이콘이 오른쪽 맨 끝으로 가야하는데 Spacer(weight(1f))가 없으면 요렇게 모여버립니다 ㅠ
또한 SpaceBetween은 child 간 간격을 똑같이 유지하므로 Text끼린 붙여놓고 Icon은 따로 띄워두어야 하는 상황이기에 요렇게 처리하는게 더 좋아보이는데 어떻게 생각하시나요 ??

2024-06-10 06:54 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/attendance/compose/component/AttendanceHistoryUserInfoCard.kt
> +        }
Row에 fillMaxWidth걸고, Text끼리 Row로 묶어버리면 Row/IIcon만 있으니까 SpaceBetween 잘 적용될겁니다.

2024-06-10 06:57 UTC, giovannijunseokim commented on app/src/main/java/org/sopt/official/feature/attendance/compose/component/AttendanceHistoryUserInfoCard.kt
> +        }
Spacer를 쓰는 것보다 Text끼리 Row로 묶는 것이 더 효율적인 방법일까요?

2024-06-12 10:49 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/attendance/compose/component/AttendanceHistoryUserInfoCard.kt
> +        }
생각해보니 개인취향쪽으로도 갈릴 수 있겠네요. 일단 이런 프로퍼티가 있다는 것만 알아둬도 좋을 것 같아요

2024-06-15 05:01 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/attendance/compose/component/AttendanceCountCard.kt
> +fun Int.toFormattedNumber(): String = "%02d회".format(this)
private fun 으로 사용하셔도 될 것 같습니다.

2024-06-16 06:50 UTC, giovannijunseokim commented on app/src/main/java/org/sopt/official/feature/attendance/compose/component/AttendanceHistoryCard.kt
> +    attendanceHistoryList: List<AttendanceHistory>,
요 내용 인지했습니다. 스트롱 스키핑 적용되어서 skippable 할텐데 Immutable Collection 사용하는 것이 좋을까요??

2024-06-16 08:19 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/feature/attendance/compose/component/AttendanceHistoryCard.kt
> +    attendanceHistoryList: List<AttendanceHistory>,
네 그래도 오픈소스기도 하고, 다른 분들한테 레퍼런스가 될 수 있으니 최대한 베스트 프랙티스로 가는게 좋을 것 같습니다.

2024-06-16 08:20 UTC, l2hyunwoo approved these changes
네 고생했습니다. 리뷰 확인하고 머지 해주세요

2024-06-16 10:00 UTC, merged