[Feature/#871] 마이페이지 오류 수정
sopt-makers/sopt-android pull request #907
Opened 2024-10-13 07:30 UTC by leeeyubin

## What is this issue?
- [x] 로그아웃 오류 수정
- [x] 한마디 편집 기능 수정 (이전  한마디 보이도록 + 토스트 띄우기)
- [x] 스탬프 초기화 수정 (성공 시 로직 작성)
- [x] 비회원 시, 둘러보기 기능 에러 수정
- [x] 비회원 시, 로그인 기능 수정 
- [x] 닉네임 설정 파일 삭제

https://github.com/user-attachments/assets/21222145-e74b-4998-a319-2c0530876c47

## Reference
- 코드를 보시다보면 저걸 왜 저렇게 고쳤을까하는 의문이 드는 곳이 많을 거라 생각하는데요.. 질문 마구마구 해주십쇼..!
- 다이얼로그를 side effect로 처리해보려다가 아직 감이 안 잡혀서.. 일단은 state로 리팩해두었어요!

2024-10-13 08:07 UTC, s9hn requested changes
개인적으로 저는 코드 일관성정도를 중요하게 여기는데요. 현재 코드는 비슷한 책임에 여러다른 방식들이 혼용되어있는 것 같아요!
uistate에 action을 분리해보는 것도 좋을 것 같아요 :)

2024-10-13 08:07 UTC, s9hn commented on feature/mypage/src/main/java/org/sopt/official/feature/mypage/mypage/MyPageViewModel.kt
> +        if (activeState == UserActiveState.UNAUTHENTICATED) _state.value = MyPageUiState.UnAuthenticated
아래에선 update를 사용하는데 여기선 세터로 다르게 사용하는 이유가 있나용

2024-10-13 08:07 UTC, s9hn commented on feature/mypage/src/main/java/org/sopt/official/feature/mypage/soptamp/sentence/AdjustSentenceActivity.kt
> +                LaunchedEffect(viewModel.sideEffect, lifecycleOwner) {
저도 궁금한건데 다음 전체 분기를 launchedEffect로 감싼 이유가 뭔가용..?

2024-10-13 08:07 UTC, s9hn commented on feature/mypage/src/main/java/org/sopt/official/feature/mypage/soptamp/sentence/AdjustSentenceSideEffect.kt
> +sealed class AdjustSentenceSideEffect {
별다른 생성자가 필요해보이진 않는데 sealed interface는 어떤가요?

2024-10-13 08:07 UTC, s9hn commented on feature/mypage/src/main/java/org/sopt/official/feature/mypage/soptamp/sentence/AdjustSentenceViewModel.kt
> +    val isConfirmed = sentence.map { sentence ->
자료구조임을 나타낼수 있는 네이밍이 좋을 것 같아요!

2024-10-13 09:48 UTC, l2hyunwoo commented on core/authimpl/src/main/java/org/sopt/official/auth/impl/api/AuthService.kt
>      @HTTP(method = "DELETE", path = "user/logout", hasBody = true)
Delete에 body 값이 안들어가는게 원칙인데 굳이 넣어줘야할 때에는 이렇게 사용하는걸로 알고 있음

2024-10-13 09:49 UTC, l2hyunwoo commented on core/authimpl/src/main/java/org/sopt/official/auth/impl/api/AuthService.kt
>      @HTTP(method = "DELETE", path = "user/logout", hasBody = true)
저거 무시하고 그냥 body 패러미터 넣으면 에러 일으킴ㅋㅋㅋ

그래서 원칙적으로는

1. 서버한테 바디 패러미터 빼달라고 하거나
2. 저렇게 사용하거나
인데 난 갠적으로 1로 쇼부치는게 더 깔끔하다고 생각하긴함. (정 안되면 2번)

2024-10-13 09:49 UTC, l2hyunwoo commented on core/authimpl/src/main/java/org/sopt/official/auth/impl/remote/DefaultRemoteAuthDataSource.kt
> +    override suspend fun logout(request: LogOutRequest) {
@s9hn 그러면 함수 네이밍 추천좀...

2024-10-13 09:54 UTC, s9hn commented on core/authimpl/src/main/java/org/sopt/official/auth/impl/remote/DefaultRemoteAuthDataSource.kt
> +    override suspend fun logout(request: LogOutRequest) {
ㅋ한번쯤은 고민해보셔야지~

2024-10-13 09:55 UTC, s9hn commented on core/authimpl/src/main/java/org/sopt/official/auth/impl/api/AuthService.kt
>      @HTTP(method = "DELETE", path = "user/logout", hasBody = true)
오.. 바디에 넣는게없는데 바디가 있는게 신기하네 하나 알아갑니다. 저도 같은이유라면 1번이 깔끔한듯

2024-10-14 03:22 UTC, leeeyubin commented on core/authimpl/src/main/java/org/sopt/official/auth/impl/repository/AuthRepositoryImpl.kt
> +    override suspend fun logout(pushToken: String) = runCatching {
pushToken을 파라미터로 받을 이유가 없다는 말씀이신가요..?! 
로그아웃 로직을 살펴보니 기존 코드는  파이어베이스에서 pushToken을 가져와 파라미터로 넣어주고 있는 것 같습니다.
파이어베이스에 저장되어 있는 토큰과 로컬 저장소에 저장되어 있는 토큰이 차이점이 있을까요.........?

2024-10-14 06:01 UTC, leeeyubin commented on feature/mypage/src/main/java/org/sopt/official/feature/mypage/soptamp/sentence/AdjustSentenceActivity.kt
> +                LaunchedEffect(viewModel.sideEffect, lifecycleOwner) {
한마디 편집 화면에서 마이페이지로 돌아가기 위해서는 토스트를 띄우고, 뒤로가기 기능을 동시에 해줘야 하는데 이는 부수효과라고 생각해서 SharedFlow를 통해 LaunchedEffect로 한번에 처리하고자 했습니다.

혹시 keyboardController가 왜 사용됐는지를 여쭤보신걸까요..?!

2024-10-14 09:40 UTC, giovannijunseokim commented on feature/mypage/src/main/java/org/sopt/official/feature/mypage/soptamp/sentence/AdjustSentenceActivity.kt
> +                LaunchedEffect(viewModel.sideEffect, lifecycleOwner) {
음 `collect`는 일종의 구독 행위인데, 구독하는 행위가 왜 `LaunchedEffect` 내부에 있는지 궁금하신 것 같아요. 저도 궁금합니다 !

2024-10-14 09:48 UTC, giovannijunseokim commented on feature/mypage/src/main/java/org/sopt/official/feature/mypage/soptamp/sentence/AdjustSentenceViewModel.kt
> +    val isConfirmed = sentence.map { sentence ->
initSentence 말씀하신거 맞죠?? 저도 동의합니다 !

2024-10-14 09:50 UTC, giovannijunseokim reviewed
고생하셨습니다~! 세훈님이 너무 잘 달아주셔서 추가로 남길만한 코멘트가 없네요!
이건 별개의 이야긴데 실력이 많이 늘으셨군요 화이팅입니다 !!

2024-10-14 18:34 UTC, leeeyubin commented on feature/mypage/src/main/java/org/sopt/official/feature/mypage/soptamp/sentence/AdjustSentenceViewModel.kt
> +    val isConfirmed = sentence.map { sentence ->
변수명 짓는 게 생각보다 쉽지 않군여..

2024-10-14 19:08 UTC, leeeyubin commented on feature/mypage/src/main/java/org/sopt/official/feature/mypage/soptamp/sentence/AdjustSentenceActivity.kt
> +                LaunchedEffect(viewModel.sideEffect, lifecycleOwner) {
아하 음,, `collect`를 통해서 구독은 하고 있지만, 제가 알기론 `flow`가 수명주기까지는 인식을 못한다고 알고 있습니다. 
그래서 `lifecycleOwner`를 통해 수명주기가 살아있을 때만 구독을 할 수 있도록 이를 `LaunchedEffect` 내부에 존재하도록 하였습니다! 

질문해주신 의도에 대한 답이 되었을까요..........?

2024-10-15 02:05 UTC, l2hyunwoo commented on feature/mypage/src/main/java/org/sopt/official/feature/mypage/soptamp/sentence/AdjustSentenceActivity.kt
> +                LaunchedEffect(viewModel.sideEffect, lifecycleOwner) {
collect가 suspend function이니까...? 정도로 대답할 수 있지 않을까유

2024-10-15 02:09 UTC, l2hyunwoo commented on feature/mypage/src/main/java/org/sopt/official/feature/mypage/mypage/MyPageActivity.kt
> +                                            onDismissRequest = viewModel::onDismiss,
이 MyPageDialog가 섹션들 사이에 있는 지 이유가 따로 있을까요?

2024-10-15 06:12 UTC, s9hn commented on core/authimpl/src/main/java/org/sopt/official/auth/impl/remote/DefaultRemoteAuthDataSource.kt
> +    override suspend fun logout(request: LogOutRequest) {
저장소는 CRUD 관련된 prefix만을 사용하려고 합니다.
개인적으로 PRND 컨벤션인 save, fetch도 나쁘지않다고 생각해요

2024-10-15 06:55 UTC, s9hn commented on feature/mypage/src/main/java/org/sopt/official/feature/mypage/soptamp/sentence/AdjustSentenceActivity.kt
> +                LaunchedEffect(viewModel.sideEffect, lifecycleOwner) {
아하 sharedFlow였군요. 왜 제공되는 collect 확장함수를 사용하지 않았나해서 궁금했습니다.
그렇다면 또 궁금한것은 Event 혹은 SideEffect들을 다음과 같은 stateless Flow로 방출할 때 유실되는 이벤트는 어떻게 관리해야 하나요?

2024-10-15 06:55 UTC, s9hn commented on core/authimpl/src/main/java/org/sopt/official/auth/impl/repository/AuthRepositoryImpl.kt
> +    override suspend fun logout(pushToken: String) = runCatching {
아하 저도 실제 사용처 찾아보니 파이어베이스 토큰을 호출해서 넣어주고 있었네요.
아마 유빈님이 작성하신 코드는 아닌 것으로 보이는데 뷰모델에서 런캐칭으로 Firebase의 토큰을 호출해주고 다음 logout함수에 전달해주고 있는 것 같아요.
저라면 Firebase에서 토큰을 가져오는 행위를 뷰모델에서 하지 않았을 것 같아요.
해당 코드는 레거시 코드이니 이번 PR에서 리팩터링 하실지는 선택에 맡기겠습니다 :)

2024-10-15 06:55 UTC, s9hn commented on feature/mypage/src/main/java/org/sopt/official/feature/mypage/soptamp/sentence/AdjustSentenceViewModel.kt
> +    val isConfirmed = sentence.map { sentence ->
isConfirmed를 얘기한거긴..합니다 ㅋㅋ isXXX는 Boolean타입을 떠올리니까요!

2024-10-15 07:01 UTC, s9hn approved these changes

2024-10-15 23:54 UTC, l2hyunwoo commented on core/authimpl/src/main/java/org/sopt/official/auth/impl/remote/DefaultRemoteAuthDataSource.kt
> +    override suspend fun logout(request: LogOutRequest) {
앱을 사용하는 입장에서 보면 유저 상태를 날리는 함수인데 save, fetch라....논리적으로 맞지 않는다고 생각하는데 어떻게 생각하시나요

2024-10-15 23:57 UTC, l2hyunwoo commented
> Compose에서 SideEffect는 화면을 그리는 기능 외의 작업을 의미한다고 생각합니다. 화면의 상태를 의미하는 state에서 다이얼로그가 보이고 있는지, 아닌지를 체크하는 것이 좋다고 생각해요!

다이얼로그나 스낵바등 알림을 띄우는 행위의 UI는 일회성 이벤트로 간주해서 effect로 관리하는게 훨씬 편합니다 (스낵바나 다이얼로그는 한번 띄워놓고 저희가 굳이 닫혀있는지 열려있는지 관리할 필요가 없자나요? 그리고 스낵바도 누르면 몇개씩 띄워지는 형태의 UI도 있구요) @giovannijunseokim

2024-10-16 05:21 UTC, l2hyunwoo approved these changes
고생하셨습니다

2024-10-16 05:32 UTC, s9hn commented on core/authimpl/src/main/java/org/sopt/official/auth/impl/remote/DefaultRemoteAuthDataSource.kt
> +    override suspend fun logout(request: LogOutRequest) {
앱을 사용하는 입장에서 보는게 잘못된 입장이라고 생각해요! 
RemoteDataSource 입장에서 보았을 때, 들어온 요청이 '원격 저장소에 있는 유저 상태를 없애줘'니까 
deleteUserInfo 라는 네이밍이 적절할 것 같아요 혹은 saveDeleted(removed)userInfo으로도 쓸수는 있을것같아요

2024-10-17 04:18 UTC, leeeyubin commented on feature/mypage/src/main/java/org/sopt/official/feature/mypage/mypage/MyPageActivity.kt
> +                                            onDismissRequest = viewModel::onDismiss,
처음에 코드를 작성할 때는 `uiState`가 `Authenticated`인 상황에서 다이얼로그를 띄우는 거라 섹션들 사이에 같이 넣어뒀었습니다.
그런데 `uiState`와 `action`은 분리하는 게 좋을 것 같다고 하셔서 현재는 바꿔주었어요!

2024-10-17 05:14 UTC, merged