[Feature/#918] fortune 추가 구현
sopt-makers/sopt-android pull request #924
Opened 2024-10-18 06:09 UTC by chattymin

## What is this issue?
- [x] 라이팅 변경
- [x] 뒤로가기시 화면 전환 로직 수정
- [x] 오늘의 운세가 아닐 경우 스낵바 추가

## Reference

https://github.com/user-attachments/assets/65ba6ccf-b19f-49c4-9fdf-2c2d0f8936e5

## Etc
baseLine이랑 개행 수정하니까 줄수가 쫘자좍 늘어나버리네요 쩝.

2024-10-18 08:55 UTC, giovannijunseokim commented on feature/notification/src/main/java/org/sopt/official/feature/notification/detail/NotificationDetailActivity.kt
> +                                                    link == HOME_FORTUNE && notification?.createdAt?.split("T")?.get(0) != LocalDate.now().toString() -> {
이 부분이 어떤 조건인지 따로 함수화하면 네이밍을 통해 어떤 조건에 아래 행동이 일어나는지 알 수 있을 것 같아요!

2024-10-18 08:57 UTC, giovannijunseokim approved these changes
고생하셨습니다 ~!

2024-10-18 12:44 UTC, l2hyunwoo requested changes
topBar 쪽 한번만 봐주실?

2024-10-18 12:44 UTC, l2hyunwoo commented on feature/notification/src/main/java/org/sopt/official/feature/notification/detail/NotificationDetailActivity.kt
> +                            ErrorSnackBar(message = "앗, 오늘의 솝마디만 볼 수 있어요.")
이런 경우라면 SnackbarContent라고 했을 것 같아요!

2024-10-18 12:58 UTC, chattymin commented on feature/notification/src/main/java/org/sopt/official/feature/notification/detail/NotificationDetailActivity.kt
> +                            )
넵 일부러 내렸습니다!

디자인 요구사항이 TopBar에 일부 걸쳐있게 상단에 스낵바가 뜨는 것이었습니다. 그래서 `snackbarHost`를 사용하게 되면 default가 바닥에 뜨는 것으로 설정되어있기 때문에 이를 사용하지 않고 화면에 넣었습니다.
위 코드와 같이 SnackBar를 상단에 띄우면 TopBar 밑에 가려져 화면에 안보이게 됩니다. 그래서 TopBar또한 content에 넣는 방식을 사용했습니다

2024-10-18 13:01 UTC, l2hyunwoo commented on feature/notification/src/main/java/org/sopt/official/feature/notification/detail/NotificationDetailActivity.kt
> +                            )
오케이 알겠습니다.

2024-10-18 13:03 UTC, chattymin commented on feature/notification/src/main/java/org/sopt/official/feature/notification/detail/NotificationDetailActivity.kt
> +                            ErrorSnackBar(message = "앗, 오늘의 솝마디만 볼 수 있어요.")
content는 일반적으로 `Composable 함수`를 파라미터로 받아올 때 주로 사용하는 것으로 생각돼요!
해당 SnackBar의 경우 String값만 받아올 수 있기 때문에 `content`가 아닌 `message`라는 이름을 사용했습니다.

혹시 이 부분은 어떻게 생각하시나요? @l2hyunwoo

2024-10-19 13:29 UTC, l2hyunwoo commented on feature/notification/src/main/java/org/sopt/official/feature/notification/detail/NotificationDetailActivity.kt
> +                            ErrorSnackBar(message = "앗, 오늘의 솝마디만 볼 수 있어요.")
SnackbarHost 내에 들어가는 내용이어서 Content라고 붙인거긴 한데, 이건 적는 사람 마음인 것 같아서.

2024-10-19 13:29 UTC, l2hyunwoo approved these changes
고생하셨습니다.

2024-10-19 14:52 UTC, s9hn approved these changes
고생하셨씀다~ 스프린트0 슈웃

2024-10-19 14:52 UTC, s9hn commented on feature/notification/src/main/java/org/sopt/official/feature/notification/detail/NotificationDetailActivity.kt
> +                                        .background(SoptTheme.colors.onSurface800)
이거 궁금했는데 background하나로 안쓰고 clip으로 따로 지정하는 이유가 있나요?

2024-10-19 14:52 UTC, s9hn commented on feature/notification/src/main/java/org/sopt/official/feature/notification/detail/NotificationDetailActivity.kt
> +                                    Spacer(modifier = Modifier.padding(14.dp))
spacer는 보통 height나 width를 이용하는데 padding이랑 차이가 딱히 없겠죠?

2024-10-20 04:09 UTC, chattymin commented on feature/notification/src/main/java/org/sopt/official/feature/notification/detail/NotificationDetailActivity.kt
> +                                        .background(SoptTheme.colors.onSurface800)
이 Activity는 현우형이 짠 뷰라... 
근데 저도 저렇게 하긴 합니다. 그래서 제 의견을 말씀드리면
백그라운드에 모양을 지정하게 되면 해당 컴포넌트는 각진 상태로 남아있되, 배경색만 해당 모양으로 됩니다.
그래서 해당 컴포넌트 자체를 깎기 위해서는 따로 clip을 해줘야 해용

2024-10-20 04:11 UTC, chattymin commented on feature/notification/src/main/java/org/sopt/official/feature/notification/detail/NotificationDetailActivity.kt
> +                                    Spacer(modifier = Modifier.padding(14.dp))
이것도 제가 짠건 아니긴 한데 ㅋㅋㅋㅋㅋㅋ
이 뷰에선 문제 없어보여요!

그저 가로로도 14만큼 할당돼서 정사각형 모양 패딩이 돼서 바로 옆에 뭐가 하나 더 붙어있다면 차이가 생길수는 있을거 같긴 하네요
물론 저도 height랑 width를 이용하긴 합니당

2024-10-20 08:09 UTC, merged