[refactor/#708] attendance Time Format 방식 수정
sopt-makers/sopt-android pull request #925
Opened 2024-10-18 08:30 UTC by t1nm1ksun

## What is this issue?
- [ ] 새로 추가된 포매터를 활용해서 kotlinx.datetime 형식의 포맷 방식을 수정합니다.

## Reference
- 수정 전 UI
<img src="https://github.com/user-attachments/assets/c9d261d3-08af-42a7-b6c6-66370e2ee5da" alt="description" width="400"/>

- 수정 후 UI
<img src="https://github.com/user-attachments/assets/e215001d-2484-4769-8cc0-7e7a2de52833" alt="description" width="400"/>

## Etc
!= "" -> .isNotBlank() 로 수정해보았습니다
기존 UI와 똑같이 뜬다면 잘 변경한 걸까요..?

2024-10-18 10:15 UTC, l2hyunwoo requested changes
한번 리뷰 확인해주세요

2024-10-18 10:15 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/data/model/attendance/SoptEventResponse.kt
> +                    timeFormat.format(endAtDateTime)
지금 문자열 리터럴 쓴 부분도 유니코드 패턴으로 사용해서 문자열 포맷팅 할 수 있지 않을까요?

2024-10-18 10:15 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/data/model/attendance/SoptEventResponse.kt
>  }
현재는 HH:mm 형태만 파싱을 하고 있는데 다른 개발자 분들이 다른 형태로 파싱을 하고 싶은 경우에는 (예를들어 세훈님은 "YYYY.MM.dd" 형태로, 저는 "HH:mm:SS"로 파싱하고 싶다면?) 어떻게 해야할까요?

2024-10-18 10:52 UTC, s9hn commented on app/src/main/java/org/sopt/official/data/model/attendance/SoptEventResponse.kt
>  }
@l2hyunwoo ㅖ? 저요?

2024-10-18 12:39 UTC, l2hyunwoo requested changes
다시 한번 고민해주시면 감사하겠습니다 🙇🏻

2024-10-18 12:39 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/data/model/attendance/SoptEventResponse.kt
> +}
이 기능이 attendance에만 사용될 기능이 아닐 것 같아서 웬만하면 core common 모듈 쪽으로 빼두는 걸 추천드릴게요.

2024-10-18 12:39 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/data/model/attendance/SoptEventResponse.kt
> +                    getTimeFormat().format(endAtDateTime)
[이 블로그](https://hyunjungchoi.tistory.com/151) 활용해서 이 부분 코드 어떻게 고칠 수 있을 지 한번 고민해보시면 좋을 것 같아요! 그러면 timeFormat 함수쪽 설계도 조금 달라져야겠죠?

2024-10-20 15:54 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/official/data/model/attendance/SoptEventResponse.kt
>  }
@t1nm1ksun getTimeFormat 함수를 TimeFormat 오브젝트에 담아두는 이유가 있을까요? 의견이 궁금합니다.

2024-10-22 14:13 UTC, t1nm1ksun commented on app/src/main/java/org/sopt/official/data/model/attendance/SoptEventResponse.kt
> +                    getTimeFormat().format(endAtDateTime)
시험만 끝나고 얼른 해보겠습니다..!! 
늦어져서 죄송합니다 ㅜㅜ

2025-07-22 07:59 UTC, closed without merging